using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[assembly: InternalsVisibleTo("sqlx-cs-pg-generator-test")]
namespace Sqlx.Postgres.Generator.Query;

[Generator]
internal class PgExecutableQueryBindGenerator : IIncrementalGenerator
{
    private const string GeneratePgBindMethodAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Query;
        
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Method)]
        public sealed class GeneratePgBindMethodAttribute : global::System.Attribute
        {
            public System.Type? Encoder { get; set; }
        }
        """;
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "GeneratePgBindMethodAttribute.g.cs",
                SourceText.From(GeneratePgBindMethodAttribute, Encoding.UTF8));
        });

        var typesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Query.GeneratePgBindMethodAttribute",
                predicate: static (_, _) => true,
                transform: static (ctx, _) =>
                    GetTargetForGeneration(ctx.SemanticModel, ctx.TargetNode))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            typesToGenerate.Collect(),
            static (spc, source) => Execute(source, spc));
    }
    
    private static BindMethodToGenerate? GetTargetForGeneration(
        SemanticModel semanticModel,
        SyntaxNode syntax)
    {
        return semanticModel.GetDeclaredSymbol(syntax) is not IMethodSymbol methodSymbol
            ? null
            : new BindMethodToGenerate(methodSymbol);
    }

    private static void Execute(
        ImmutableArray<BindMethodToGenerate?> methodsToGenerate,
        SourceProductionContext context)
    {
        if (methodsToGenerate.IsDefaultOrEmpty) return;

        StringBuilder builder = new(
            """
            // <auto-generated/>
            #nullable enable
            
            using Sqlx.Core.Query;
            using Sqlx.Postgres.Exceptions;
            using Sqlx.Postgres.Type;
            
            namespace Sqlx.Postgres.Query;
            
            public static partial class ExecutableQueryExtensions
            {
            """);
        foreach (BindMethodToGenerate? methodToGenerate in methodsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            if (methodToGenerate is null)
            {
                continue;
            }

            if (!methodToGenerate.Validate(context))
            {
                continue;
            }
            
            var sourceCode = GenerateBindMethod(methodToGenerate);
            builder.AppendLine();
            foreach (var line in sourceCode.Split('\n'))
            {
                builder.Append("    ");
                builder.AppendLine(line);
            }
        }

        builder.Append('}');
        builder.AppendLine();
        
        context.AddSource(
            "BindMethods.g.cs",
            SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static string GenerateBindMethod(BindMethodToGenerate bindMethodToGenerate)
    {
        var valueTypeName = bindMethodToGenerate.ValueType.ToDisplayString();
        string bindTypeName;
        if (bindMethodToGenerate.IsValueArray)
        {
            ITypeSymbol resultTypeElement = SourceGenerationHelper.NotNullType(
                ((IArrayTypeSymbol)bindMethodToGenerate.ValueType).ElementType);
            var resultTypeElementName = resultTypeElement.ToDisplayString();
            var tempDecoderTypeName = bindMethodToGenerate.EncoderType?.ToDisplayString()
                                      ?? resultTypeElementName;
            bindTypeName = resultTypeElement.IsValueType
                ? $"PgArrayTypeStruct<{resultTypeElementName}, {tempDecoderTypeName}>"
                : $"PgArrayTypeClass<{resultTypeElementName}, {tempDecoderTypeName}>";
        }
        else
        {
            bindTypeName = bindMethodToGenerate.EncoderType?.ToDisplayString() ?? valueTypeName;
        }
        
        var valueParameterName = bindMethodToGenerate.ValueParameterName;
        var signature = $"public static partial IQuery {bindMethodToGenerate.Name}(this IQuery query, {bindMethodToGenerate.ValueType.ToDisplayString()}{(bindMethodToGenerate.IsValueNullable ? '?' : string.Empty)} {valueParameterName})";
        if (bindMethodToGenerate.IsValueNullable)
        {
            var isNullableCheck = bindMethodToGenerate.ValueType.IsValueType;
            return $$"""
                 {{signature}}
                 {
                     return {{(isNullableCheck ? $"!{valueParameterName}.HasValue" : $"{valueParameterName} is null")}}
                         ? query.BindNull<{{valueTypeName}}>()
                         : PgException.CheckIfIs<IQuery, PgExecutableQuery>(query)
                             .Encode<{{valueTypeName}}, {{bindTypeName}}>({{valueParameterName}}{{(isNullableCheck ? ".Value" : "")}});
                 }
                 """;
        }

        return $"""
             {signature} =>
                 PgException.CheckIfIs<IQuery, PgExecutableQuery>(query)
                     .Encode<{valueTypeName}, {bindTypeName}>({valueParameterName});
             """;
    }
}
