using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sqlx.Postgres.Generator.Query;

internal class PgToParamImplementationGenerator : ISourceGenerationPipeline<PgToParamToGenerate>
{
    public string AttributeName => "Sqlx.Postgres.Generator.Query.ToParamAttribute";

    public bool IsValidSyntax(SyntaxNode node, CancellationToken cancellationToken) =>
        node.IsProductType;

    public PgToParamToGenerate? CreateGenerationContext(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol ||
            context.TargetNode is not TypeDeclarationSyntax typeDeclarationSyntax)
        {
            return null;
        }

        cancellationToken.ThrowIfCancellationRequested();
        return new PgToParamToGenerate(typeSymbol, typeDeclarationSyntax);
    }

    public void ExecuteGeneration(
        SourceProductionContext context,
        ImmutableArray<PgToParamToGenerate> implementationsToGenerate)
    {
        ExecutePgToParamGeneration(context, implementationsToGenerate);
    }

    public static void ExecutePgToParamGeneration(
        SourceProductionContext context,
        ImmutableArray<PgToParamToGenerate> implementationsToGenerate)
    {
        if (implementationsToGenerate.IsEmpty)
        {
            return;
        }

        foreach (PgToParamToGenerate pgToParamToGenerate in implementationsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            if (!pgToParamToGenerate.Validate(context))
            {
                continue;
            }

            var fromRowImplementation = GeneratePgBindManyTypeImplementation(pgToParamToGenerate);
            context.AddSource(
                $"{pgToParamToGenerate.ShortName}.IBindMany.g.cs",
                SourceText.From(fromRowImplementation, Encoding.UTF8));
        }
    }

    private static string GeneratePgBindManyTypeImplementation(
        PgToParamToGenerate pgToParamToGenerate)
    {
        StringBuilder builder = new(
            """
            // <auto-generated/>
            #nullable enable
            """);
        builder.AppendLine();
        if (!string.IsNullOrEmpty(pgToParamToGenerate.ContainingNamespace))
        {
            builder.AppendLine();
            builder.Append("namespace ")
                .Append(pgToParamToGenerate.ContainingNamespace)
                .AppendLine(";");
        }

        builder.AppendLine();
        builder.Append(pgToParamToGenerate.DeclaredAccessibility.GetModifierToken())
            .Append(" partial ")
            .Append(pgToParamToGenerate.IsStruct ? "struct " : "class ")
            .Append(pgToParamToGenerate.ShortName)
            .AppendLine(" : global::Sqlx.Core.Query.IBindMany<global::Sqlx.Postgres.Query.IPgBindable>");
        builder.AppendLine("{");
        builder.AppendLine("    public void BindMany(global::Sqlx.Postgres.Query.IPgBindable bindable)");
        builder.AppendLine("    {");
        foreach (IPropertySymbol property in pgToParamToGenerate.Properties)
        {
            if (property.Type.IsNullable)
            {
                ITypeSymbol finalType = property.Type.AsNotNullType();
                builder.Append("        if (this.")
                    .Append(property.Name)
                    .AppendLine(" is null)");
                builder.AppendLine("        {");
                builder.Append("            bindable.BindNull<")
                    .AppendFullName(finalType)
                    .AppendLine(">();");
                builder.AppendLine("        }");
                builder.AppendLine("        else");
                builder.AppendLine("        {");
                builder.Append("            bindable.BindPg<")
                    .AppendFullName(finalType)
                    .Append(',')
                    .Append(finalType.GetIPgDbType()!)
                    .Append(">(this.")
                    .Append(property.Name)
                    .Append(finalType.IsValueType ? ".Value" : "")
                    .AppendLine(");");
                builder.AppendLine("        }");
            }
            else
            {
                builder.Append("        bindable.BindPg<")
                    .AppendFullName(property.Type)
                    .Append(',')
                    .Append(property.Type.GetIPgDbType()!)
                    .Append(">(this.")
                    .Append(property.Name)
                    .AppendLine(");");
            }
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
