//HintName: DecodeMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Result;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Result;

public static partial class DataRowExtensions
{
    public static partial string? GetString(this IPgDataRow dataRow, int index)
    {
        if (dataRow.IsNull(index))
        {
            return null;
        }
        return dataRow.GetPgNotNull<string, PgString>(index);
    }
}
