//HintName: GeneratePgDecodeMethodAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Result;

[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Method)]
public sealed class GeneratePgDecodeMethodAttribute : global::System.Attribute
{
    public System.Type? Decoder { get; set; }
}