//HintName: DecodeMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Result;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Result;

public static partial class DataRowExtensions
{
    public static partial string GetStringNotNull(this IDataRow dataRow, string name) =>
        PgException.CheckIfIs<IDataRow, IPgDataRow>(dataRow)
            .GetPgNotNull<string, PgString>(dataRow.IndexOf(name));
}
