//HintName: DecodeMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Result;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Result;

public static partial class DataRowExtensions
{
    public static partial bool GetPgBoolean(this IDataRow dataRow, int index) =>
        PgException.CheckIfIs<IDataRow, IPgDataRow>(dataRow)
            .GetPgNotNull<bool, PgBool>(index);
}
