//HintName: BindMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Query;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Query;

public static partial class Bindable
{
    public static partial void Bind(this IBindable bindable, System.Guid?[]? value)
    {
        PgException.CheckIfIs<IBindable, IPgBindable>(bindable)
                .BindPgNullableClass<System.Guid?[], PgArrayTypeStruct<System.Guid, PgUuid>>(value);
    }
}
