//HintName: BindMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Query;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Query;

public static partial class Query
{
    public static partial IQuery Bind(this IQuery query, string? value)
    {
        return value is null
            ? query.BindNull<string>()
            : PgException.CheckIfIs<IQuery, PgExecutableQuery>(query)
                .Encode<string, string>(value);
    }
}
