//HintName: BindMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Query;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Query;

public static partial class Query
{
    public static partial IQuery Bind(this IQuery query, System.Guid?[]? value)
    {
        return value is null
            ? query.BindNull<System.Guid?[]>()
            : PgException.CheckIfIs<IQuery, PgExecutableQuery>(query)
                .Encode<System.Guid?[], PgArrayTypeStruct<System.Guid, PgUuid>>(value);
    }
}
