//HintName: BindMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Query;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Query;

public static partial class Query
{
    public static partial IBindable Bind(this IBindable bindable, PgTimeTz?[]? value)
    {
        return PgException.CheckIfIs<IBindable, IPgBindable>(bindable)
                .BindPgNullableClass<PgTimeTz?[], PgArrayTypeStruct<PgTimeTz, PgTimeTz>>(value);
    }
}
