//HintName: BindMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Query;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Query;

public static partial class Query
{
    public static partial IBindable Bind(this IBindable bindable, System.Guid value) =>
        PgException.CheckIfIs<IBindable, IPgBindable>(bindable)
            .BindPg<System.Guid, PgUuid>(value);
}
