//HintName: GeneratePgBindMethodAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Query;

[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Method)]
public sealed class GeneratePgBindMethodAttribute : global::System.Attribute
{
    public System.Type? Encoder { get; set; }
}