//HintName: DecodeMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Result;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Result;

public static partial class DataRowExtensions
{
    public static partial string?[]? GetPgStrongArray(this IDataRow dataRow, int index)
    {
        if (dataRow.IsNull(index))
        {
            return null;
        }
        return PgException.CheckIfIs<IDataRow, PgDataRow>(dataRow)
            .DecodeNotNull<string?[], PgArrayTypeClass<string, PgString>>(index);
    }
}
