//HintName: PgEnumTypes.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Exceptions;
using Sqlx.Core.Result;
using Sqlx.Postgres.Column;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Pool;
using Sqlx.Postgres.Query;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generated.Type;

public static class PgEnumTypes
{
    public static void Bind(this IPgBindable pgBindable, TestEnum enumValue)
    {
        pgBindable.Bind<TestEnum, PgTestEnum>(enumValue);
    }

    public static void Bind(this IPgBindable pgBindable, TestEnum? enumValue)
    {
        pgBindable.BindVal<TestEnum, PgTestEnum>(enumValue);
    }

    public static TestEnum GetTestEnumNotNull(this IPgDataRow pgDataRow, int index)
    {
        return pgDataRow.GetPgNotNull<TestEnum, PgTestEnum>(index);
    }

    public static TestEnum GetTestEnumNotNull(this IPgDataRow pgDataRow, string name)
    {
        return pgDataRow.GetPgNotNull<TestEnum, PgTestEnum>(name);
    }

    public static TestEnum? GetTestEnum(this IPgDataRow pgDataRow, int index)
    {
        return pgDataRow.GetPgVal<TestEnum, PgTestEnum>(index);
    }

    public static TestEnum? GetTestEnum(this IPgDataRow pgDataRow, string name)
    {
        return pgDataRow.GetPgVal<TestEnum, PgTestEnum>(name);
    }

}
