//HintName: PgTestEnum.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Buffer;
using Sqlx.Core.Exceptions;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generated.Type;

public abstract class PgTestEnum : IPgDbType<TestEnum>
{
    private PgTestEnum() {}

    public static void Encode(TestEnum value, IBufferWriter<byte> buffer)
    {
        buffer.WriteInt((int)value);
    }

    public static TestEnum DecodeBytes(ref PgBinaryValue value)
    {
        return (TestEnum)value.Buffer.ReadInt();
    }

    public static TestEnum DecodeText(in PgTextValue value)
    {
        if (int.TryParse(value.Chars, out var temp))
        {
            return (TestEnum)temp;
        }
        throw ColumnDecodeException.Create<TestEnum>(
            value.ColumnMetadata,
            "Could not parse characters into a valid int");
    }
    
    public static PgTypeInfo DbType { get; } = PgTypeInfo.Int4;
    
    public static bool IsCompatible(PgTypeInfo typeInfo)
    {
        return typeInfo == DbType;
    }
}