//HintName: PgNameAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator;

[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
public class PgNameAttribute : global::System.Attribute
{
    public string Value { get; }
    
    public PgNameAttribute(string value)
    {
        Value = value;
    }
}