//HintName: PgTestEnum.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Buffer;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generated.Type;

public abstract class PgTestEnum : IPgDbType<TestEnum>
{
    private PgTestEnum() {}

    public static void Encode(TestEnum value, IBufferWriter<byte> buffer)
    {
        buffer.WriteString(value.ToEncodeString());
    }

    public static TestEnum DecodeBytes(ref PgBinaryValue value)
    {
        return TestEnum.FromChars(value.Buffer.ReadString(), value.ColumnMetadata);
    }

    public static TestEnum DecodeText(in PgTextValue value)
    {
        return TestEnum.FromChars(value.Chars, value.ColumnMetadata);
    }

    public static PgTypeInfo DbType { get; } = PgTypeInfo.Text;
    
    public static bool IsCompatible(PgTypeInfo typeInfo)
    {
        return typeInfo == DbType;
    }
}