//HintName: BindMethods.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Query;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Query;

public static partial class ExecutableQueryExtensions
{
    public static partial IQuery Bind(this IQuery query, PgTimeTz value) =>
        PgException.CheckIfIs<IQuery, PgExecutableQuery>(query)
            .Encode<PgTimeTz, PgTimeTz>(value);
}
