//HintName: PgNameAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator;

/// <summary>
/// Source generation attribute applied to properties or parameters that need to use a
/// different name when generating serialization or deserialization interfaces for enum,
/// composite or row types. This can also be used for text backed enum wrapper types.
/// </summary>
[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter)]
public class PgNameAttribute : global::System.Attribute
{
    public string Value { get; }
    
    public PgNameAttribute(string value)
    {
        Value = value;
    }
}