//HintName: PgPropertySkipAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator;

[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property)]
public sealed class PgPropertySkipAttribute : global::System.Attribute
{
}