//HintName: WrapperEnumTypes.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

public static class WrapperEnumTypes
{
    extension(TestEnum enumValue)
    {
        public global::System.ReadOnlySpan<char> ToEncodeString()
        {
            return enumValue switch
            {
                TestEnum.None => "none",
                TestEnum.Single => "single",
                TestEnum.MultipleWords => "multiple_words",
                TestEnum.Value_With4Words => "value__with4_words",
                _ => throw new global::System.InvalidOperationException($"Attempted to encode an unknown enum variant, '{enumValue}'"),
            };
        }

        public static TestEnum FromChars(in global::System.ReadOnlySpan<char> chars)
        {
            return chars switch
            {
                "none" => TestEnum.None,
                "single" => TestEnum.Single,
                "multiple_words" => TestEnum.MultipleWords,
                "value__with4_words" => TestEnum.Value_With4Words,
                _ => throw new global::System.InvalidOperationException($"Attempted to decode an unknown enum variant with name, '{chars}'"),
            };
        }
    }

    public static void Bind(this global::Sqlx.Postgres.Query.IPgBindable pgBindable, TestEnum enumValue)
    {
        pgBindable.Bind(enumValue.ToEncodeString());
    }

    public static void Bind(this global::Sqlx.Postgres.Query.IPgBindable pgBindable, TestEnum? enumValue)
    {
        if (enumValue.HasValue)
        {
            pgBindable.Bind(enumValue.Value.ToEncodeString());
        }
        else
        {
            pgBindable.BindNull<string>();
        }
    }

    public static TestEnum GetTestEnumNotNull(this global::Sqlx.Postgres.Result.IPgDataRow pgDataRow, int index)
    {
        return TestEnum.FromChars(pgDataRow.GetPgNotNull<string, global::Sqlx.Postgres.Type.PgString>(index));
    }

    public static TestEnum GetTestEnumNotNull(this global::Sqlx.Postgres.Result.IPgDataRow pgDataRow, string name)
    {
        int index = pgDataRow.IndexOf(name);
        return TestEnum.FromChars(pgDataRow.GetPgNotNull<string, global::Sqlx.Postgres.Type.PgString>(index));
    }

    public static TestEnum? GetTestEnum(this global::Sqlx.Postgres.Result.IPgDataRow pgDataRow, int index)
    {
        if (pgDataRow.IsNull(index)) return null;
        return TestEnum.FromChars(pgDataRow.GetPgNotNull<string, global::Sqlx.Postgres.Type.PgString>(index));
    }

    public static TestEnum? GetTestEnum(this global::Sqlx.Postgres.Result.IPgDataRow pgDataRow, string name)
    {
        int index = pgDataRow.IndexOf(name);
        if (pgDataRow.IsNull(index)) return null;
        return TestEnum.FromChars(pgDataRow.GetPgNotNull<string, global::Sqlx.Postgres.Type.PgString>(index));
    }

}
