//HintName: PgEnumTypes.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

public static class PgEnumTypes
{
    public static ValueTask MapTestEnumAsync(this global::Sqlx.Postgres.Pool.IPgConnectionPool pgConnectionPool, global::System.Threading.CancellationToken cancellationToken = default)
    {
        return pgConnectionPool.MapEnumAsync<global::TestEnum, PgTestEnum>(cancellationToken);
    }

    extension(global::TestEnum enumValue)
    {
        public global::System.ReadOnlySpan<char> ToEncodeString()
        {
            return enumValue switch
            {
                global::TestEnum.None => "None",
                global::TestEnum.Single => "Single",
                global::TestEnum.MultipleWords => "MultipleWords",
                global::TestEnum.Value_With4Words => "Value_With4Words",
                _ => throw global::Sqlx.Core.Exceptions.ColumnEncodeException.Create<global::TestEnum>(PgTestEnum.DbType.TypeOid.Inner, $"Attempted to encode an unknown enum variant, '{enumValue}'"),
            };
        }

        public static global::TestEnum FromChars(in global::System.ReadOnlySpan<char> chars, in global::Sqlx.Postgres.Column.PgColumnMetadata columnMetadata)
        {
            return chars switch
            {
                "None" => global::TestEnum.None,
                "Single" => global::TestEnum.Single,
                "MultipleWords" => global::TestEnum.MultipleWords,
                "Value_With4Words" => global::TestEnum.Value_With4Words,
                _ => throw global::Sqlx.Core.Exceptions.ColumnDecodeException.Create<global::TestEnum, global::Sqlx.Postgres.Column.PgColumnMetadata>(columnMetadata, $"Attempted to decode an unknown enum variant with name, '{chars}'"),
            };
        }
    }

}
