//HintName: TestWrapperType.IPgDbType.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

public partial struct TestWrapperType : IPgDbType<TestWrapperType>
{
    private static TestWrapperType FromInner(System.Int32 inner)
    {
        return new TestWrapperType { Id = inner};
    }

    public static PgTypeInfo DbType => Sqlx.Postgres.Type.PgInt.DbType;
    
    public static void Encode(TestWrapperType value, IBufferWriter<byte> buffer)
    {
        Sqlx.Postgres.Type.PgInt.Encode(value.Id, buffer);
    }

    public static TestWrapperType DecodeBytes(in PgBinaryValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgInt.DecodeBytes(in value));
    }
    
    public static TestWrapperType DecodeText(in PgTextValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgInt.DecodeText(in value));
    }
    
    public static bool IsCompatible(PgTypeInfo typeInfo)
    {
        return Sqlx.Postgres.Type.PgInt.IsCompatible(typeInfo);
    }
}