//HintName: TestWrapperIds.IPgDbType.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

public partial struct TestWrapperIds : IPgDbType<TestWrapperIds>
{
    private static TestWrapperIds FromInner(System.Int32[] inner)
    {
        return new TestWrapperIds { Inner = inner};
    }

    public static PgTypeInfo DbType => Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.DbType;
    
    public static void Encode(TestWrapperIds value, IBufferWriter<byte> buffer)
    {
        Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.Encode(value.Inner, buffer);
    }

    public static TestWrapperIds DecodeBytes(in PgBinaryValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.DecodeBytes(in value));
    }
    
    public static TestWrapperIds DecodeText(in PgTextValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.DecodeText(in value));
    }
    
    public static bool IsCompatible(PgTypeInfo typeInfo)
    {
        return Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.IsCompatible(typeInfo);
    }
}