//HintName: PgEnumTypes.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Exceptions;
using Sqlx.Core.Result;
using Sqlx.Postgres.Column;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Pool;
using Sqlx.Postgres.Query;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generator.Type;

public static class PgEnumTypes
{
    public static ValueTask MapPostgresEnumTypeAsync(this IPgConnectionPool pgConnectionPool, CancellationToken cancellationToken = default)
    {
        return pgConnectionPool.MapEnumAsync<PostgresEnumType, PgPostgresEnumType>(cancellationToken);
    }

    extension(PostgresEnumType enumValue)
    {
        public ReadOnlySpan<char> ToEncodeString()
        {
            return enumValue switch
            {
                PostgresEnumType.None => "None",
                PostgresEnumType.Some => "Some",
                _ => throw ColumnEncodeException.Create<PostgresEnumType>(PgPostgresEnumType.DbType.TypeOid.Inner, $"Attempted to encode an unknown enum variant, '{enumValue}'"),
            };
        }

        public static PostgresEnumType FromChars(in ReadOnlySpan<char> chars, in PgColumnMetadata columnMetadata)
        {
            return chars switch
            {
                "None" => PostgresEnumType.None,
                "Some" => PostgresEnumType.Some,
                _ => throw ColumnDecodeException.Create<PostgresEnumType, PgColumnMetadata>(columnMetadata, $"Attempted to decode an unknown enum variant with name, '{chars}'"),
            };
        }
    }

    public static void Bind(this IPgBindable pgBindable, PostgresEnumType enumValue)
    {
        pgBindable.Bind<PostgresEnumType, PgPostgresEnumType>(enumValue);
    }

    public static void Bind(this IPgBindable pgBindable, PostgresEnumType? enumValue)
    {
        pgBindable.BindVal<PostgresEnumType, PgPostgresEnumType>(enumValue);
    }

}
