//HintName: TestWrapperTYpe.IPgDbType.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace ;

public partial struct TestWrapperType : IPgDbType<TestWrapperType>
{
    private static TestWrapperTYpe FromInner(Int32 inner)
    {
        return new TestWrapperTYpe { Id = inner};
    }

    public static PgTypeInfo DbType => Sqlx.Postgres.Type.PgInt.DbType;
    
    public static void Encode(TestWrapperTYpe value, IBufferWriter<byte> buffer)
    {
        Sqlx.Postgres.Type.PgInt.Encode(value.Id, buffer);
    }

    public static TestWrapperTYpe DecodeBytes(in PgBinaryValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgInt.DecodeBytes(in value));
    }
    
    public static TestWrapperTYpe DecodeText(in PgTextValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgInt.DecodeText(in value));
    }
    
    public static bool IsCompatible(PgTypeInfo typeInfo)
    {
        return Sqlx.Postgres.Type.PgInt.IsCompatible(typeInfo);
    }
}