//HintName: TestRow.IFromRow.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestRow : global::Sqlx.Core.Result.IFromRow<global::Sqlx.Postgres.Result.IPgDataRow, TestRow>
{
    public static TestRow FromRow(global::Sqlx.Postgres.Result.IPgDataRow dataRow)
    {
        var indexId = dataRow.IndexOf("Id");
        var indexInner = dataRow.IndexOf("Inner");
        var indexJsonField = dataRow.IndexOf("JsonField");
        var indexOptionalJsonField = dataRow.IndexOf("OptionalJsonField");
        return new TestRow
        {
            Id = dataRow.GetPgNotNull<System.Int32,Sqlx.Postgres.Type.PgInt>(indexId),
            Inner = InnerRow.FromRow(dataRow),
            JsonField = dataRow.GetJsonNotNull<JsonFieldType>(indexJsonField),
            OptionalJsonField = dataRow.GetJson<JsonFieldType>(indexOptionalJsonField),
        };
    }
}
