//HintName: TestParamBinding.IBindMany.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestParamBinding : global::Sqlx.Core.Query.IBindMany<global::Sqlx.Postgres.Query.IPgBindable>
{
    public void BindMany(global::Sqlx.Postgres.Query.IPgBindable bindable)
    {
        bindable.BindPg<System.Int32,Sqlx.Postgres.Type.PgInt>(this.Id);
        bindable.BindPg<System.String,Sqlx.Postgres.Type.PgString>(this.Id);
    }
}
