//HintName: TestRow.IFromRow.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Result;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

public partial struct TestRow : IFromRow<IPgDataRow, TestRow>
{
    public static TestRow FromRow(IPgDataRow dataRow)
    {
        return new TestRow
        {
            Id = dataRow.GetIntNotNull("Id"),
            Inner = InnerRow.FromRow(dataRow),
            JsonField = dataRow.GetJsonNotNull<JsonFieldType>("JsonField"),
            OptionalJsonField = dataRow.GetJson<JsonFieldType>("OptionalJsonField"),
        };
    }
}
