//HintName: WrapperEnumAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
public sealed class WrapperEnumAttribute : global::System.Attribute
{
    public required Sqlx.Postgres.Generator.Type.EnumRepresentation Representation  { get; init; }

    public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
}