//HintName: TestRow.IFromRow.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestRow : global::Sqlx.Core.Result.IFromRow<global::Sqlx.Postgres.Result.IPgDataRow, TestRow>
{
    public static TestRow FromRow(global::Sqlx.Postgres.Result.IPgDataRow dataRow)
    {
        var indexBoolField = dataRow.IndexOf("BoolField");
        var indexByteField = dataRow.IndexOf("ByteField");
        var indexShortField = dataRow.IndexOf("ShortField");
        var indexIntField = dataRow.IndexOf("IntField");
        var indexLongField = dataRow.IndexOf("LongField");
        var indexFloatField = dataRow.IndexOf("FloatField");
        var indexDoubleField = dataRow.IndexOf("DoubleField");
        var indexTimeField = dataRow.IndexOf("TimeField");
        var indexDateField = dataRow.IndexOf("DateField");
        var indexDateTimeField = dataRow.IndexOf("DateTimeField");
        var indexDateTimeOffsetField = dataRow.IndexOf("DateTimeOffsetField");
        var indexDecimalField = dataRow.IndexOf("DecimalField");
        var indexStringField = dataRow.IndexOf("StringField");
        var indexGuidField = dataRow.IndexOf("GuidField");
        var indexIpNetworkField = dataRow.IndexOf("IpNetworkField");
        var indexBitArrayField = dataRow.IndexOf("BitArrayField");
        var indexLongRangeField = dataRow.IndexOf("LongRangeField");
        var indexIntRangeField = dataRow.IndexOf("IntRangeField");
        var indexDateRangeField = dataRow.IndexOf("DateRangeField");
        var indexDateTimeRangeField = dataRow.IndexOf("DateTimeRangeField");
        var indexDateTimeOffsetRangeField = dataRow.IndexOf("DateTimeOffsetRangeField");
        var indexDecimalRangeField = dataRow.IndexOf("DecimalRangeField");
        var indexBytesField = dataRow.IndexOf("BytesField");
        var indexPointField = dataRow.IndexOf("PointField");
        var indexIntArrayField = dataRow.IndexOf("IntArrayField");
        var indexNullableIntField = dataRow.IndexOf("NullableIntField");
        var indexWrapperEnumTypeField = dataRow.IndexOf("WrapperEnumTypeField");
        var indexPostgresEnumTypeField = dataRow.IndexOf("PostgresEnumTypeField");
        return new TestRow(
            BoolField: dataRow.GetPgNotNull<System.Boolean,Sqlx.Postgres.Type.PgBool>(indexBoolField),
            ByteField: dataRow.GetPgNotNull<System.SByte,Sqlx.Postgres.Type.PgChar>(indexByteField),
            ShortField: dataRow.GetPgNotNull<System.Int16,Sqlx.Postgres.Type.PgShort>(indexShortField),
            IntField: dataRow.GetPgNotNull<System.Int32,Sqlx.Postgres.Type.PgInt>(indexIntField),
            LongField: dataRow.GetPgNotNull<System.Int64,Sqlx.Postgres.Type.PgLong>(indexLongField),
            FloatField: dataRow.GetPgNotNull<System.Single,Sqlx.Postgres.Type.PgFloat>(indexFloatField),
            DoubleField: dataRow.GetPgNotNull<System.Double,Sqlx.Postgres.Type.PgDouble>(indexDoubleField),
            TimeField: dataRow.GetPgNotNull<System.TimeOnly,Sqlx.Postgres.Type.PgTime>(indexTimeField),
            DateField: dataRow.GetPgNotNull<System.DateOnly,Sqlx.Postgres.Type.PgDate>(indexDateField),
            DateTimeField: dataRow.GetPgNotNull<System.DateTime,Sqlx.Postgres.Type.PgDateTime>(indexDateTimeField),
            DateTimeOffsetField: dataRow.GetPgNotNull<System.DateTimeOffset,Sqlx.Postgres.Type.PgDateTimeOffset>(indexDateTimeOffsetField),
            DecimalField: dataRow.GetPgNotNull<System.Decimal,Sqlx.Postgres.Type.PgDecimal>(indexDecimalField),
            StringField: dataRow.GetPgNotNull<System.String,Sqlx.Postgres.Type.PgString>(indexStringField),
            GuidField: dataRow.GetPgNotNull<System.Guid,Sqlx.Postgres.Type.PgUuid>(indexGuidField),
            IpNetworkField: dataRow.GetPgNotNull<System.Net.IPNetwork,Sqlx.Postgres.Type.PgIpNetwork>(indexIpNetworkField),
            BitArrayField: dataRow.GetPgNotNull<System.Collections.BitArray,Sqlx.Postgres.Type.PgBitString>(indexBitArrayField),
            LongRangeField: dataRow.GetPgNotNull<Sqlx.Postgres.Type.PgRange<System.Int64>,Sqlx.Postgres.Type.PgRangeType<System.Int64, Sqlx.Postgres.Type.PgLong>>(indexLongRangeField),
            IntRangeField: dataRow.GetPgNotNull<Sqlx.Postgres.Type.PgRange<System.Int32>,Sqlx.Postgres.Type.PgRangeType<System.Int32, Sqlx.Postgres.Type.PgInt>>(indexIntRangeField),
            DateRangeField: dataRow.GetPgNotNull<Sqlx.Postgres.Type.PgRange<System.DateOnly>,Sqlx.Postgres.Type.PgRangeType<System.DateOnly, Sqlx.Postgres.Type.PgDate>>(indexDateRangeField),
            DateTimeRangeField: dataRow.GetPgNotNull<Sqlx.Postgres.Type.PgRange<System.DateTime>,Sqlx.Postgres.Type.PgRangeType<System.DateTime, Sqlx.Postgres.Type.PgDateTime>>(indexDateTimeRangeField),
            DateTimeOffsetRangeField: dataRow.GetPgNotNull<Sqlx.Postgres.Type.PgRange<System.DateTimeOffset>,Sqlx.Postgres.Type.PgRangeType<System.DateTimeOffset, Sqlx.Postgres.Type.PgDateTimeOffset>>(indexDateTimeOffsetRangeField),
            DecimalRangeField: dataRow.GetPgNotNull<Sqlx.Postgres.Type.PgRange<System.Decimal>,Sqlx.Postgres.Type.PgRangeType<System.Decimal, Sqlx.Postgres.Type.PgDecimal>>(indexDecimalRangeField),
            BytesField: dataRow.GetPgNotNull<System.Byte[],Sqlx.Postgres.Type.PgBytea>(indexBytesField),
            PointField: dataRow.GetPgNotNull<Sqlx.Postgres.Type.PgPoint>(indexPointField),
            IntArrayField: dataRow.GetPgNotNull<System.Int32[],Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>>(indexIntArrayField),
            NullableIntField: dataRow.IsNull(indexNullableIntField) ? null : dataRow.GetPgNotNull<System.Int32,Sqlx.Postgres.Type.PgInt>(indexNullableIntField),
            WrapperEnumTypeField: dataRow.GetWrapperEnumTypeNotNull>(indexWrapperEnumTypeField),
            PostgresEnumTypeField: dataRow.GetPgNotNull<PostgresEnumType,Sqlx.Postgres.Generator.Type.PgPostgresEnumType>(indexPostgresEnumTypeField));
    }
}
