//HintName: WrapperEnumTypes.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Exceptions;
using Sqlx.Core.Result;
using Sqlx.Postgres.Column;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Pool;
using Sqlx.Postgres.Query;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generator.Type;

public static class WrapperEnumTypes
{
    public static void Bind(this IPgBindable pgBindable, WrapperEnumType enumValue)
    {
        pgBindable.Bind((int)enumValue);
    }

    public static void Bind(this IPgBindable pgBindable, WrapperEnumType? enumValue)
    {
        if (enumValue.HasValue)
        {
            pgBindable.Bind((int)enumValue.Value);
        }
        else
        {
            pgBindable.BindNull<int>();
        }
    }

    public static WrapperEnumType GetWrapperEnumTypeNotNull(this IPgDataRow pgDataRow, int index)
    {
        return (WrapperEnumType)pgDataRow.GetIntNotNull(index);
    }

    public static WrapperEnumType GetWrapperEnumTypeNotNull(this IPgDataRow pgDataRow, string name)
    {
        return (WrapperEnumType)pgDataRow.GetIntNotNull(name);
    }

    public static WrapperEnumType? GetWrapperEnumType(this IPgDataRow pgDataRow, int index)
    {
        if (pgDataRow.IsNull(index)) return null;
        return (WrapperEnumType)pgDataRow.GetIntNotNull(index);
    }

    public static WrapperEnumType? GetWrapperEnumType(this IPgDataRow pgDataRow, string name)
    {
        int index = pgDataRow.IndexOf(name);
        if (pgDataRow.IsNull(index)) return null;
        return (WrapperEnumType)pgDataRow.GetIntNotNull(index);
    }

}
