//HintName: PgEnumTypes.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Exceptions;
using Sqlx.Core.Result;
using Sqlx.Postgres.Column;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Pool;
using Sqlx.Postgres.Query;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generator.Type;

public static class PgEnumTypes
{
    public static ValueTask MapTestEnumAsync(this IPgConnectionPool pgConnectionPool, CancellationToken cancellationToken = default)
    {
        return pgConnectionPool.MapEnumAsync<TestEnum, PgTestEnum>(cancellationToken);
    }

    extension(TestEnum enumValue)
    {
        public ReadOnlySpan<char> ToEncodeString()
        {
            return enumValue switch
            {
                TestEnum.None => "none",
                TestEnum.Single => "single",
                TestEnum.MultipleWords => "multi_words",
                _ => throw ColumnEncodeException.Create<TestEnum>(PgTestEnum.DbType.TypeOid.Inner, $"Attempted to encode an unknown enum variant, '{enumValue}'"),
            };
        }

        public static TestEnum FromChars(in ReadOnlySpan<char> chars, in PgColumnMetadata columnMetadata)
        {
            return chars switch
            {
                "none" => TestEnum.None,
                "single" => TestEnum.Single,
                "multi_words" => TestEnum.MultipleWords,
                _ => throw ColumnDecodeException.Create<TestEnum, PgColumnMetadata>(columnMetadata, $"Attempted to decode an unknown enum variant with name, '{chars}'"),
            };
        }
    }

    public static void Bind(this IPgBindable pgBindable, TestEnum enumValue)
    {
        pgBindable.Bind<TestEnum, PgTestEnum>(enumValue);
    }

    public static void Bind(this IPgBindable pgBindable, TestEnum? enumValue)
    {
        pgBindable.BindVal<TestEnum, PgTestEnum>(enumValue);
    }

}
