//HintName: PgCompositeAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

/// <summary>
/// Source generation attribute applied to class/struct types that will be read from and
/// written to the database as a custom Postgres composite type. The <see cref="Name" />
/// property supplies the name of type (schema qualified) to allow for finding the type OID
/// during connection pool startup. You can also set type level rules for how the property
/// names are mapped to the database composite type attributes.
/// </summary>
[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)]
public sealed class PgCompositeAttribute : global::System.Attribute
{
    public required string Name { get; init; }

    public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
}