//HintName: TestRow.IFromRow.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestRow : global::Sqlx.Core.Result.IFromRow<global::Sqlx.Postgres.Result.IPgDataRow, TestRow>
{
    public static TestRow FromRow(global::Sqlx.Postgres.Result.IPgDataRow dataRow)
    {
        var indexId = dataRow.IndexOf("Id");
        var indexInner = dataRow.IndexOf("Inner");
        var indexJsonField = dataRow.IndexOf("JsonField");
        var indexOptionalJsonField = dataRow.IndexOf("OptionalJsonField");
        return new TestRow
        {
            Id = dataRow.GetPgNotNull<global::System.Int32,global::Sqlx.Postgres.Type.PgInt>(indexId),
            Inner = global::InnerRow.FromRow(dataRow),
            JsonField = dataRow.GetPgNotNull<global::JsonFieldType,global::Sqlx.Postgres.Type.PgJson<global::JsonFieldType>>(indexJsonField),
            OptionalJsonField = dataRow.IsNull(indexOptionalJsonField) ? null : dataRow.GetPgNotNull<global::JsonFieldType,PgJson<global::JsonFieldType>>(indexOptionalJsonField),
        };
    }
}
