//HintName: WrapperTypeAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

/// <summary>
/// Source generation attribute applied to wrapper struct types for another type that is
/// implicitly able to be sent to and received from the database. This extends the type
/// definition, implementing the IPgDbType interface for itself where the implementation
/// defers to the underlining type.
/// </summary>
[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct)]
public sealed class WrapperTypeAttribute : global::System.Attribute
{
}