//HintName: TestWrapperIds.IPgDbType.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestWrapperIds : global::Sqlx.Postgres.Type.IPgDbType<TestWrapperIds>
{
    private static TestWrapperIds FromInner(System.Int32[] inner)
    {
        return new TestWrapperIds { Inner = inner};
    }

    public static global::Sqlx.Postgres.Type.PgTypeInfo DbType => Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.DbType;
    
    public static void Encode(TestWrapperIds value, global::System.Bufferss.IBufferWriter<byte> buffer)
    {
        Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.Encode(value.Inner, buffer);
    }

    public static TestWrapperIds DecodeBytes(in global::Sqlx.Postgres.Result.PgBinaryValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.DecodeBytes(in value));
    }
    
    public static TestWrapperIds DecodeText(in global::Sqlx.Postgres.Result.PgTextValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.DecodeText(in value));
    }
    
    public static bool IsCompatible(global::Sqlx.Postgres.Type.PgTypeInfo typeInfo)
    {
        return Sqlx.Postgres.Type.PgArrayTypeStruct<System.Int32, Sqlx.Postgres.Type.PgInt>.IsCompatible(typeInfo);
    }
}