//HintName: TestComposite.IBindMany.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestComposite : global::Sqlx.Core.Query.IBindMany<global::Sqlx.Postgres.Query.IPgBindable>
{
    public void BindMany(global::Sqlx.Postgres.Query.IPgBindable bindable)
    {
        bindable.BindPg<System.Int32,Sqlx.Postgres.Type.PgInt>(this.Id);
        bindable.BindPg<System.String,Sqlx.Postgres.Type.PgString>(this.Name);
        if (this.Bytes is null)
        {
            bindable.BindNull<System.Byte[]>();
        }
        else
        {
            bindable.BindPg<System.Byte[],Sqlx.Postgres.Type.PgBytea>(this.Bytes);
        }
        bindable.BindPg<Sqlx.Postgres.Type.PgRange<System.Int64>,Sqlx.Postgres.Type.PgRangeType<System.Int64, Sqlx.Postgres.Type.PgLong>>(this.LongRange);
    }
}
