//HintName: PgEnumTypes.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

public static class PgEnumTypes
{
    public static ValueTask MapTestEnumAsync(this global::Sqlx.Postgres.Pool.IPgConnectionPool pgConnectionPool, global::System.Threading.CancellationToken cancellationToken = default)
    {
        return pgConnectionPool.MapEnumAsync<global::TestEnum, PgTestEnum>(cancellationToken);
    }

    extension(global::TestEnum enumValue)
    {
        public global::System.ReadOnlySpan<char> ToEncodeString()
        {
            return enumValue switch
            {
                global::TestEnum.None => "none",
                global::TestEnum.Single => "single",
                global::TestEnum.MultipleWords => "multi_words",
                _ => throw global::Sqlx.Core.Exceptions.ColumnEncodeException.Create<global::TestEnum>(PgTestEnum.DbType.TypeOid.Inner, $"Attempted to encode an unknown enum variant, '{enumValue}'"),
            };
        }

        public static global::TestEnum FromChars(in global::System.ReadOnlySpan<char> chars, in global::Sqlx.Postgres.Column.PgColumnMetadata columnMetadata)
        {
            return chars switch
            {
                "none" => global::TestEnum.None,
                "single" => global::TestEnum.Single,
                "multi_words" => global::TestEnum.MultipleWords,
                _ => throw global::Sqlx.Core.Exceptions.ColumnDecodeException.Create<global::TestEnum, global::Sqlx.Postgres.Column.PgColumnMetadata>(columnMetadata, $"Attempted to decode an unknown enum variant with name, '{chars}'"),
            };
        }
    }

}
