//HintName: TestComposite.IPgUdt.g.cs
// <auto-generated/>
#nullable enable

namespace ;

public partial struct TestComposite : global::Sqlx.Postgres.Type.IPgUdt<TestComposite>
{
    public static global::Sqlx.Postgres.Type.PgTypeInfo DbType { get; set; } = global::Sqlx.Postgres.Type.PgTypeInfo.Unknown;
    
    public static string TypeName => "test_composite";
    
    public static void Encode(TestComposite value, global::System.Buffers.IBufferWriter<byte> buffer)
    {
        global::Sqlx.Postgres.Type.PgRecordEncoder.EncodeRecord(value, buffer);
    }

    public static TestComposite DecodeBytes(in global::Sqlx.Postgres.Result.PgBinaryValue value)
    {
        return global::Sqlx.Postgres.Type.PgRecordDecoder.DecodeBinary<TestComposite>(in value);
    }
    
    public static TestComposite DecodeText(in global::Sqlx.Postgres.Result.PgTextValue value)
    {
        return global::Sqlx.Postgres.Type.PgRecordDecoder.DecodeText<TestComposite>(in value);
    }
    
    public static bool IsCompatible(global::Sqlx.Postgres.Type.PgTypeInfo typeInfo)
    {
        return typeInfo == DbType;
    }
}
