//HintName: PgPostgresEnumType.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Buffer;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generator.Type;

public abstract class PgPostgresEnumType : IPgUdt<PostgresEnumType>
{
    private PgPostgresEnumType() {}

    public static PgTypeInfo DbType { get; set; } = PgTypeInfo.Unknown;
    
    public static string TypeName => "postgres_enum_type";
    
    public static bool IsCompatible(PgTypeInfo typeInfo)
    {
        return typeInfo == DbType;
    }

    public static void Encode(PostgresEnumType value, IBufferWriter<byte> buffer)
    {
        buffer.WriteString(value.ToEncodeString());
    }

    public static PostgresEnumType DecodeBytes(in PgBinaryValue value)
    {
        var buff = value.Buffer;
        return PostgresEnumType.FromChars(buff.ReadString(), value.ColumnMetadata);
    }

    public static PostgresEnumType DecodeText(in PgTextValue value)
    {
        return PostgresEnumType.FromChars(value.Chars, value.ColumnMetadata);
    }
}