//HintName: WrapperEnumTypes.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Exceptions;
using Sqlx.Core.Result;
using Sqlx.Postgres.Column;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Pool;
using Sqlx.Postgres.Query;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generator.Type;

public static class WrapperEnumTypes
{
    public static void Bind(this IPgBindable pgBindable, TestEnum enumValue)
    {
        pgBindable.Bind((int)enumValue);
    }

    public static void Bind(this IPgBindable pgBindable, TestEnum? enumValue)
    {
        if (enumValue.HasValue)
        {
            pgBindable.Bind((int)enumValue.Value);
        }
        else
        {
            pgBindable.BindNull<int>();
        }
    }

    public static TestEnum GetTestEnumNotNull(this IPgDataRow pgDataRow, int index)
    {
        return (TestEnum)pgDataRow.GetIntNotNull(index);
    }

    public static TestEnum GetTestEnumNotNull(this IPgDataRow pgDataRow, string name)
    {
        return (TestEnum)pgDataRow.GetIntNotNull(name);
    }

    public static TestEnum? GetTestEnum(this IPgDataRow pgDataRow, int index)
    {
        if (pgDataRow.IsNull(index)) return null;
        return (TestEnum)pgDataRow.GetIntNotNull(index);
    }

    public static TestEnum? GetTestEnum(this IPgDataRow pgDataRow, string name)
    {
        int index = pgDataRow.IndexOf(name);
        if (pgDataRow.IsNull(index)) return null;
        return (TestEnum)pgDataRow.GetIntNotNull(index);
    }

}
