//HintName: TestParamBinding.IBindMany.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Query;
using Sqlx.Postgres.Query;

public partial struct TestParamBinding : IBindMany<IPgBindable>
{
    public void BindMany(IPgBindable bindable)
    {
        bindable.Bind(this.Id);
        bindable.Bind(this.Id);
    }
}
