//HintName: WrapperEnumTypes.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Core.Exceptions;
using Sqlx.Core.Result;
using Sqlx.Postgres.Column;
using Sqlx.Postgres.Exceptions;
using Sqlx.Postgres.Pool;
using Sqlx.Postgres.Query;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generator.Type;

public static class WrapperEnumTypes
{
    extension(TestEnum enumValue)
    {
        public ReadOnlySpan<char> ToEncodeString()
        {
            return enumValue switch
            {
                TestEnum.None => "none",
                TestEnum.Single => "single",
                TestEnum.MultipleWords => "multiple_words",
                TestEnum.Value_With4Words => "value__with4_words",
                _ => throw new InvalidOperationException($"Attempted to encode an unknown enum variant, '{enumValue}'"),
            };
        }

        public static TestEnum FromChars(in ReadOnlySpan<char> chars)
        {
            return chars switch
            {
                "none" => TestEnum.None,
                "single" => TestEnum.Single,
                "multiple_words" => TestEnum.MultipleWords,
                "value__with4_words" => TestEnum.Value_With4Words,
                _ => throw new InvalidOperationException($"Attempted to decode an unknown enum variant with name, '{chars}'"),
            };
        }
    }

    public static void Bind(this IPgBindable pgBindable, TestEnum enumValue)
    {
        pgBindable.Bind(enumValue.ToEncodeString());
    }

    public static void Bind(this IPgBindable pgBindable, TestEnum? enumValue)
    {
        if (enumValue.HasValue)
        {
            pgBindable.Bind(enumValue.Value.ToEncodeString());
        }
        else
        {
            pgBindable.BindNull<string>();
        }
    }

    public static TestEnum GetTestEnumNotNull(this IPgDataRow pgDataRow, int index)
    {
        return TestEnum.FromChars(pgDataRow.GetStringNotNull(index));
    }

    public static TestEnum GetTestEnumNotNull(this IPgDataRow pgDataRow, string name)
    {
        return TestEnum.FromChars(pgDataRow.GetStringNotNull(name));
    }

    public static TestEnum? GetTestEnum(this IPgDataRow pgDataRow, int index)
    {
        if (pgDataRow.IsNull(index)) return null;
        return TestEnum.FromChars(pgDataRow.GetStringNotNull(index));
    }

    public static TestEnum? GetTestEnum(this IPgDataRow pgDataRow, string name)
    {
        int index = pgDataRow.IndexOf(name);
        if (pgDataRow.IsNull(index)) return null;
        return TestEnum.FromChars(pgDataRow.GetStringNotNull(index));
    }

}
