//HintName: PgEnumAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
public sealed class PgEnumAttribute : global::System.Attribute
{
    public required string Name { get; set; }

    public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
}