//HintName: JsonFieldAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

/// <summary>
/// Source generation attribute applied to properties that represent JSON data from the
/// database deserialized as the properties type. 
/// </summary>
[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter)]
public sealed class JsonFieldAttribute : global::System.Attribute
{
}