//HintName: TestComposite.IBindMany.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Query;
using Sqlx.Postgres.Query;

public partial struct TestComposite : IBindMany<IPgBindable>
{
    public void BindMany(IPgBindable bindable)
    {
        bindable.Bind(this.Id);
        bindable.Bind(this.Name);
        bindable.Bind(this.Bytes);
        bindable.Bind(this.LongRange);
    }
}
