//HintName: PgTestEnum.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

public abstract class PgTestEnum : global::Sqlx.Postgres.Type.IPgUdt<global::TestEnum>
{
    private PgTestEnum() {}

    public static global::Sqlx.Postgres.Type.PgTypeInfo DbType { get; set; } = global::Sqlx.Postgres.Type.PgTypeInfo.Unknown;
    
    public static string TypeName => "test_enum";
    
    public static bool IsCompatible(global::Sqlx.Postgres.Type.PgTypeInfo typeInfo)
    {
        return typeInfo == DbType;
    }

    public static void Encode(global::TestEnum value, global::System.Buffers.IBufferWriter<byte> buffer)
    {
        global::Sqlx.Core.Buffer.BufferExtensions.WriteString(buffer, value.ToEncodeString());
    }

    public static global::TestEnum DecodeBytes(in global::Sqlx.Postgres.Result.PgBinaryValue value)
    {
        var buff = value.Buffer;
        return global::TestEnum.FromChars(
            global::Sqlx.Core.Buffer.BufferExtensions.ReadString(ref buff),
            value.ColumnMetadata);
    }

    public static global::TestEnum DecodeText(in global::Sqlx.Postgres.Result.PgTextValue value)
    {
        return global::TestEnum.FromChars(value.Chars, value.ColumnMetadata);
    }
}