//HintName: TestWrapperType.IPgDbType.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestWrapperType : global::Sqlx.Postgres.Type.IPgDbType<TestWrapperType>
{
    private static TestWrapperType FromInner(System.Int32 inner)
    {
        return new TestWrapperType { Id = inner};
    }

    public static global::Sqlx.Postgres.Type.PgTypeInfo DbType => Sqlx.Postgres.Type.PgInt.DbType;
    
    public static void Encode(TestWrapperType value, global::System.Bufferss.IBufferWriter<byte> buffer)
    {
        Sqlx.Postgres.Type.PgInt.Encode(value.Id, buffer);
    }

    public static TestWrapperType DecodeBytes(in global::Sqlx.Postgres.Result.PgBinaryValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgInt.DecodeBytes(in value));
    }
    
    public static TestWrapperType DecodeText(in global::Sqlx.Postgres.Result.PgTextValue value)
    {
        return FromInner(Sqlx.Postgres.Type.PgInt.DecodeText(in value));
    }
    
    public static bool IsCompatible(global::Sqlx.Postgres.Type.PgTypeInfo typeInfo)
    {
        return Sqlx.Postgres.Type.PgInt.IsCompatible(typeInfo);
    }
}