//HintName: TestParamBinding.IPgBinaryCopyRow.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestParamBinding : global::Sqlx.Postgres.Copy.IPgBinaryCopyRow
{
    public static short ColumnCount => 2;
}
