//HintName: TestRow.IFromRow.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Result;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

public partial struct TestRow : IFromRow<IPgDataRow, TestRow>
{
    public static TestRow FromRow(IPgDataRow dataRow)
    {
        return new TestRow(
            BoolField: dataRow.GetBooleanNotNull("BoolField"),
            ByteField: dataRow.GetByteNotNull("ByteField"),
            ShortField: dataRow.GetShortNotNull("ShortField"),
            IntField: dataRow.GetIntNotNull("IntField"),
            LongField: dataRow.GetLongNotNull("LongField"),
            FloatField: dataRow.GetFloatNotNull("FloatField"),
            DoubleField: dataRow.GetDoubleNotNull("DoubleField"),
            TimeField: dataRow.GetTimeNotNull("TimeField"),
            DateField: dataRow.GetDateNotNull("DateField"),
            DateTimeField: dataRow.GetDateTimeNotNull("DateTimeField"),
            DateTimeOffsetField: dataRow.GetDateTimeOffsetNotNull("DateTimeOffsetField"),
            DecimalField: dataRow.GetDecimalNotNull("DecimalField"),
            StringField: dataRow.GetStringNotNull("StringField"),
            GuidField: dataRow.GetGuidNotNull("GuidField"),
            IpNetworkField: dataRow.GetIpNetworkNotNull("IpNetworkField"),
            BitArrayField: dataRow.GetBitArrayNotNull("BitArrayField"),
            LongRangeField: dataRow.GetPgRangeLongNotNull("LongRangeField"),
            IntRangeField: dataRow.GetPgRangeIntNotNull("IntRangeField"),
            DateRangeField: dataRow.GetPgRangeDateNotNull("DateRangeField"),
            DateTimeRangeField: dataRow.GetPgRangeDateTimeNotNull("DateTimeRangeField"),
            DateTimeOffsetRangeField: dataRow.GetPgRangeDateTimeOffsetNotNull("DateTimeOffsetRangeField"),
            DecimalRangeField: dataRow.GetPgRangeDecimalNotNull("DecimalRangeField"),
            BytesField: dataRow.GetBytesNotNull("BytesField"),
            PointField: dataRow.GetPgNotNull("PointField"),
            IntArrayField: dataRow.GetIntArrayNotNull("IntArrayField"),
            NullableIntField: dataRow.GetInt("NullableIntField"),
            WrapperEnumTypeField: dataRow.GetWrapperEnumTypeNotNull("WrapperEnumTypeField"),
            PostgresEnumTypeField: dataRow.GetPostgresEnumTypeNotNull("PostgresEnumTypeField"));
    }
}
