//HintName: TestComposite.IFromRow.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Result;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

public partial struct TestComposite : IFromRow<IPgDataRow, TestComposite>
{
    public static TestComposite FromRow(IPgDataRow dataRow)
    {
        return new TestComposite
        {
            Id = dataRow.GetIntNotNull("Id"),
            Name = dataRow.GetStringNotNull("Name"),
            Bytes = dataRow.GetBytes("Bytes"),
            LongRange = dataRow.GetPgRangeLongNotNull("LongRange"),
        };
    }
}
