//HintName: WrapperEnumTypes.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

public static class WrapperEnumTypes
{
    public static global::System.ReadOnlySpan<char> global_TestEnum_ToEncodeString(global::TestEnum enumValue)
    {
        return enumValue switch
        {
            global::TestEnum.None => "None",
            global::TestEnum.Single => "Single",
            global::TestEnum.MultipleWords => "MultipleWords",
            global::TestEnum.Value_With4Words => "Value_With4Words",
            _ => throw new global::System.InvalidOperationException($"Attempted to encode an unknown enum variant, '{enumValue}'"),
        };
    }

    public static global::TestEnum global_TestEnum_FromChars(in global::System.ReadOnlySpan<char> chars)
    {
        return chars switch
        {
            "None" => global::TestEnum.None,
            "Single" => global::TestEnum.Single,
            "MultipleWords" => global::TestEnum.MultipleWords,
            "Value_With4Words" => global::TestEnum.Value_With4Words,
            _ => throw new global::System.InvalidOperationException($"Attempted to decode an unknown enum variant with name, '{chars}'"),
        };
    }
}
