//HintName: ToPgBinaryCopyRowAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Copy;

/// <summary>
/// Source generation attribute applied to class/struct types that represent a binary copy
/// in row. Applying this attribute generates a <see cref="Sqlx.Core.Query.IBindMany{T}"/>
/// implementation where every readable property is bound to the query in the order they are
/// declared in the type definition as well as the <c>ColumnCount</c> property as the number
/// of properties found to bind.
/// </summary>
[global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)]
public sealed class ToPgBinaryCopyRowAttribute : global::System.Attribute
{
}