//HintName: TestComposite.IBindMany.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestComposite : global::Sqlx.Core.Query.IBindMany<global::Sqlx.Postgres.Query.IPgBindable>
{
    public void BindMany(global::Sqlx.Postgres.Query.IPgBindable bindable)
    {
        bindable.BindPg<global::System.Int32,global::Sqlx.Postgres.Type.PgInt>(this.Id);
        bindable.BindPg<global::System.String,global::Sqlx.Postgres.Type.PgString>(this.Name);
        if (this.Bytes is null)
        {
            bindable.BindNull<global::System.Byte[]>();
        }
        else
        {
            bindable.BindPg<global::System.Byte[],global::Sqlx.Postgres.Type.PgBytea>(this.Bytes);
        }
        bindable.BindPg<global::Sqlx.Postgres.Type.PgRange<global::System.Int64>,global::Sqlx.Postgres.Type.PgRangeType<global::System.Int64, global::Sqlx.Postgres.Type.PgLong>>(this.LongRange);
    }
}
