//HintName: TestComposite.IFromRow.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Result;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

public partial struct TestComposite : IFromRow<IPgDataRow, TestComposite>
{
    public static TestComposite FromRow(IPgDataRow dataRow)
    {
        return new TestComposite
        {
            Id = dataRow.GetPgNotNull<System.Int32,Sqlx.Postgres.Type.PgInt>("Id"),
            Name = dataRow.GetPgNotNull<System.String,Sqlx.Postgres.Type.PgString>("Name"),
            Bytes = dataRow.IsNull(dataRow.IndexOf("Bytes")) ? null : dataRow.GetPgNotNull<System.Byte[],Sqlx.Postgres.Type.PgBytea>("Bytes"),
            LongRange = dataRow.GetPgNotNull<Sqlx.Postgres.Type.PgRange<System.Int64>,Sqlx.Postgres.Type.PgRangeType<System.Int64, Sqlx.Postgres.Type.PgLong>>("LongRange"),
        };
    }
}
