//HintName: PgEnumTypes.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

public static class PgEnumTypes
{
    public static ValueTask MapPostgresEnumTypeAsync(this global::Sqlx.Postgres.Pool.IPgConnectionPool pgConnectionPool, global::System.Threading.CancellationToken cancellationToken = default)
    {
        return pgConnectionPool.MapEnumAsync<global::PostgresEnumType, PgPostgresEnumType>(cancellationToken);
    }

    extension(global::PostgresEnumType enumValue)
    {
        public global::System.ReadOnlySpan<char> ToEncodeString()
        {
            return enumValue switch
            {
                global::PostgresEnumType.None => "None",
                global::PostgresEnumType.Some => "Some",
                _ => throw global::Sqlx.Core.Exceptions.ColumnEncodeException.Create<global::PostgresEnumType>(PgPostgresEnumType.DbType.TypeOid.Inner, $"Attempted to encode an unknown enum variant, '{enumValue}'"),
            };
        }

        public static global::PostgresEnumType FromChars(in global::System.ReadOnlySpan<char> chars, in global::Sqlx.Postgres.Column.PgColumnMetadata columnMetadata)
        {
            return chars switch
            {
                "None" => global::PostgresEnumType.None,
                "Some" => global::PostgresEnumType.Some,
                _ => throw global::Sqlx.Core.Exceptions.ColumnDecodeException.Create<global::PostgresEnumType, global::Sqlx.Postgres.Column.PgColumnMetadata>(columnMetadata, $"Attempted to decode an unknown enum variant with name, '{chars}'"),
            };
        }
    }

}
