//HintName: TestRow.IFromRow.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestRow : global::Sqlx.Core.Result.IFromRow<global::Sqlx.Postgres.Result.IPgDataRow, TestRow>
{
    public static TestRow FromRow(global::Sqlx.Postgres.Result.IPgDataRow dataRow)
    {
        var indexBoolField = dataRow.IndexOf("BoolField");
        var indexByteField = dataRow.IndexOf("ByteField");
        var indexShortField = dataRow.IndexOf("ShortField");
        var indexIntField = dataRow.IndexOf("IntField");
        var indexLongField = dataRow.IndexOf("LongField");
        var indexFloatField = dataRow.IndexOf("FloatField");
        var indexDoubleField = dataRow.IndexOf("DoubleField");
        var indexTimeField = dataRow.IndexOf("TimeField");
        var indexDateField = dataRow.IndexOf("DateField");
        var indexDateTimeField = dataRow.IndexOf("DateTimeField");
        var indexDateTimeOffsetField = dataRow.IndexOf("DateTimeOffsetField");
        var indexDecimalField = dataRow.IndexOf("DecimalField");
        var indexStringField = dataRow.IndexOf("StringField");
        var indexGuidField = dataRow.IndexOf("GuidField");
        var indexIpNetworkField = dataRow.IndexOf("IpNetworkField");
        var indexBitArrayField = dataRow.IndexOf("BitArrayField");
        var indexLongRangeField = dataRow.IndexOf("LongRangeField");
        var indexIntRangeField = dataRow.IndexOf("IntRangeField");
        var indexDateRangeField = dataRow.IndexOf("DateRangeField");
        var indexDateTimeRangeField = dataRow.IndexOf("DateTimeRangeField");
        var indexDateTimeOffsetRangeField = dataRow.IndexOf("DateTimeOffsetRangeField");
        var indexDecimalRangeField = dataRow.IndexOf("DecimalRangeField");
        var indexBytesField = dataRow.IndexOf("BytesField");
        var indexPointField = dataRow.IndexOf("PointField");
        var indexIntArrayField = dataRow.IndexOf("IntArrayField");
        var indexNullableIntField = dataRow.IndexOf("NullableIntField");
        var indexWrapperEnumTypeField = dataRow.IndexOf("WrapperEnumTypeField");
        var indexPostgresEnumTypeField = dataRow.IndexOf("PostgresEnumTypeField");
        return new TestRow(
            BoolField: dataRow.GetPgNotNull<global::System.Boolean,global::Sqlx.Postgres.Type.PgBool>(indexBoolField),
            ByteField: dataRow.GetPgNotNull<global::System.SByte,global::Sqlx.Postgres.Type.PgChar>(indexByteField),
            ShortField: dataRow.GetPgNotNull<global::System.Int16,global::Sqlx.Postgres.Type.PgShort>(indexShortField),
            IntField: dataRow.GetPgNotNull<global::System.Int32,global::Sqlx.Postgres.Type.PgInt>(indexIntField),
            LongField: dataRow.GetPgNotNull<global::System.Int64,global::Sqlx.Postgres.Type.PgLong>(indexLongField),
            FloatField: dataRow.GetPgNotNull<global::System.Single,global::Sqlx.Postgres.Type.PgFloat>(indexFloatField),
            DoubleField: dataRow.GetPgNotNull<global::System.Double,global::Sqlx.Postgres.Type.PgDouble>(indexDoubleField),
            TimeField: dataRow.GetPgNotNull<global::System.TimeOnly,global::Sqlx.Postgres.Type.PgTime>(indexTimeField),
            DateField: dataRow.GetPgNotNull<global::System.DateOnly,global::Sqlx.Postgres.Type.PgDate>(indexDateField),
            DateTimeField: dataRow.GetPgNotNull<global::System.DateTime,global::Sqlx.Postgres.Type.PgDateTime>(indexDateTimeField),
            DateTimeOffsetField: dataRow.GetPgNotNull<global::System.DateTimeOffset,global::Sqlx.Postgres.Type.PgDateTimeOffset>(indexDateTimeOffsetField),
            DecimalField: dataRow.GetPgNotNull<global::System.Decimal,global::Sqlx.Postgres.Type.PgDecimal>(indexDecimalField),
            StringField: dataRow.GetPgNotNull<global::System.String,global::Sqlx.Postgres.Type.PgString>(indexStringField),
            GuidField: dataRow.GetPgNotNull<global::System.Guid,global::Sqlx.Postgres.Type.PgUuid>(indexGuidField),
            IpNetworkField: dataRow.GetPgNotNull<global::System.Net.IPNetwork,global::Sqlx.Postgres.Type.PgIpNetwork>(indexIpNetworkField),
            BitArrayField: dataRow.GetPgNotNull<global::System.Collections.BitArray,global::Sqlx.Postgres.Type.PgBitString>(indexBitArrayField),
            LongRangeField: dataRow.GetPgNotNull<global::Sqlx.Postgres.Type.PgRange<global::System.Int64>,global::Sqlx.Postgres.Type.PgRangeType<global::System.Int64, global::Sqlx.Postgres.Type.PgLong>>(indexLongRangeField),
            IntRangeField: dataRow.GetPgNotNull<global::Sqlx.Postgres.Type.PgRange<global::System.Int32>,global::Sqlx.Postgres.Type.PgRangeType<global::System.Int32, global::Sqlx.Postgres.Type.PgInt>>(indexIntRangeField),
            DateRangeField: dataRow.GetPgNotNull<global::Sqlx.Postgres.Type.PgRange<global::System.DateOnly>,global::Sqlx.Postgres.Type.PgRangeType<global::System.DateOnly, global::Sqlx.Postgres.Type.PgDate>>(indexDateRangeField),
            DateTimeRangeField: dataRow.GetPgNotNull<global::Sqlx.Postgres.Type.PgRange<global::System.DateTime>,global::Sqlx.Postgres.Type.PgRangeType<global::System.DateTime, global::Sqlx.Postgres.Type.PgDateTime>>(indexDateTimeRangeField),
            DateTimeOffsetRangeField: dataRow.GetPgNotNull<global::Sqlx.Postgres.Type.PgRange<global::System.DateTimeOffset>,global::Sqlx.Postgres.Type.PgRangeType<global::System.DateTimeOffset, global::Sqlx.Postgres.Type.PgDateTimeOffset>>(indexDateTimeOffsetRangeField),
            DecimalRangeField: dataRow.GetPgNotNull<global::Sqlx.Postgres.Type.PgRange<global::System.Decimal>,global::Sqlx.Postgres.Type.PgRangeType<global::System.Decimal, global::Sqlx.Postgres.Type.PgDecimal>>(indexDecimalRangeField),
            BytesField: dataRow.GetPgNotNull<global::System.Byte[],global::Sqlx.Postgres.Type.PgBytea>(indexBytesField),
            PointField: dataRow.GetPgNotNull<global::Sqlx.Postgres.Type.PgPoint>(indexPointField),
            IntArrayField: dataRow.GetPgNotNull<global::System.Int32[],global::Sqlx.Postgres.Type.PgArrayTypeStruct<global::System.Int32, global::Sqlx.Postgres.Type.PgInt>>(indexIntArrayField),
            NullableIntField: dataRow.IsNull(indexNullableIntField) ? null : dataRow.GetPgNotNull<global::System.Int32,global::Sqlx.Postgres.Type.PgInt>(indexNullableIntField),
            WrapperEnumTypeField: (WrapperEnumType)dataRow.GetPgNotNull<global::System.Int32,global::Sqlx.Postgres.Type.PgInt>(indexWrapperEnumTypeField),
            PostgresEnumTypeField: dataRow.GetPgNotNull<global::PostgresEnumType,global::Sqlx.Postgres.Generator.Type.PgPostgresEnumType>(indexPostgresEnumTypeField));
    }
}
