//HintName: TestComposite.IFromRow.g.cs
// <auto-generated/>
#nullable enable

public partial struct TestComposite : global::Sqlx.Core.Result.IFromRow<global::Sqlx.Postgres.Result.IPgDataRow, TestComposite>
{
    public static TestComposite FromRow(global::Sqlx.Postgres.Result.IPgDataRow dataRow)
    {
        var indexId = dataRow.IndexOf("Id");
        var indexName = dataRow.IndexOf("Name");
        var indexBytes = dataRow.IndexOf("Bytes");
        var indexLongRange = dataRow.IndexOf("LongRange");
        return new TestComposite
        {
            Id = dataRow.GetPgNotNull<global::System.Int32,global::Sqlx.Postgres.Type.PgInt>(indexId),
            Name = dataRow.GetPgNotNull<global::System.String,global::Sqlx.Postgres.Type.PgString>(indexName),
            Bytes = dataRow.IsNull(indexBytes) ? null : dataRow.GetPgNotNull<global::System.Byte[],global::Sqlx.Postgres.Type.PgBytea>(indexBytes),
            LongRange = dataRow.GetPgNotNull<global::Sqlx.Postgres.Type.PgRange<global::System.Int64>,global::Sqlx.Postgres.Type.PgRangeType<global::System.Int64, global::Sqlx.Postgres.Type.PgLong>>(indexLongRange),
        };
    }
}
