//HintName: TestComposite.IPgUdt.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace ;

public partial struct TestComposite : IPgUdt<TestComposite>
{
    public static PgTypeInfo DbType { get; set; } = PgTypeInfo.Unknown;
    
    public static string TypeName => "test_composite";
    
    public static void Encode(TestComposite value, IBufferWriter<byte> buffer)
    {
        PgRecordEncoder.EncodeRecord(value, buffer);
    }

    public static TestComposite DecodeBytes(ref PgBinaryValue value)
    {
        return PgRecordDecoder.DecodeBinary<TestComposite>(ref value);
    }
    
    public static TestComposite DecodeText(in PgTextValue value)
    {
        return PgRecordDecoder.DecodeText<TestComposite>(in value);
    }
    
    public static bool IsCompatible(PgTypeInfo typeInfo)
    {
        return typeInfo == DbType;
    }
}