//HintName: PgTestEnum.g.cs
// <auto-generated/>
#nullable enable

using System.Buffers;
using Sqlx.Core.Buffer;
using Sqlx.Postgres.Result;
using Sqlx.Postgres.Type;

namespace Sqlx.Postgres.Generator.Type;

public abstract class PgTestEnum : IPgUdt<TestEnum>
{
    private PgTestEnum() {}

    public static PgTypeInfo DbType { get; set; } = PgTypeInfo.Unknown;
    
    public static string TypeName => "test_enum";
    
    public static bool IsCompatible(PgTypeInfo typeInfo)
    {
        return typeInfo == DbType;
    }

    public static void Encode(TestEnum value, IBufferWriter<byte> buffer)
    {
        buffer.WriteString(value.ToEncodeString());
    }

    public static TestEnum DecodeBytes(in PgBinaryValue value)
    {
        var buff = value.Buffer;
        return TestEnum.FromChars(buff.ReadString(), value.ColumnMetadata);
    }

    public static TestEnum DecodeText(in PgTextValue value)
    {
        return TestEnum.FromChars(value.Chars, value.ColumnMetadata);
    }
}