//HintName: TestParamBinding.IPgBinaryCopyRow.g.cs
// <auto-generated/>
#nullable enable

using Sqlx.Postgres.Copy;

public partial struct TestParamBinding : IPgBinaryCopyRow
{
    public static short ColumnCount => 2;
}
