//HintName: PgPostgresEnumType.g.cs
// <auto-generated/>
#nullable enable

namespace Sqlx.Postgres.Generator.Type;

public abstract class PgPostgresEnumType : global::Sqlx.Postgres.Type.IPgUdt<PostgresEnumType>
{
    private PgPostgresEnumType() {}

    public static global::Sqlx.Postgres.Type.PgTypeInfo DbType { get; set; } = global::Sqlx.Postgres.Type.PgTypeInfo.Unknown;
    
    public static string TypeName => "postgres_enum_type";
    
    public static bool IsCompatible(global::Sqlx.Postgres.Type.PgTypeInfo typeInfo)
    {
        return typeInfo == DbType;
    }

    public static void Encode(PostgresEnumType value, global::System.Buffers.IBufferWriter<byte> buffer)
    {
        global::Sqlx.Core.Buffer.BufferExtensions.WriteString(buffer, value.ToEncodeString());
    }

    public static PostgresEnumType DecodeBytes(in global::Sqlx.Postgres.Result.PgBinaryValue value)
    {
        var buff = value.Buffer;
        return PostgresEnumType.FromChars(
            global::Sqlx.Core.Buffer.BufferExtensions.ReadString(ref buff),
            value.ColumnMetadata);
    }

    public static PostgresEnumType DecodeText(in global::Sqlx.Postgres.Result.PgTextValue value)
    {
        return PostgresEnumType.FromChars(value.Chars, value.ColumnMetadata);
    }
}