using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Sqlx.Postgres.Generator.Query;
using Sqlx.Postgres.Generator.Result;

namespace Sqlx.Postgres.Generator.Type;

internal static class PgCompositeImplementationGenerator
{
    public static PgCompositeToGenerate? GetPgCompositeToGenerate(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol ||
            context.TargetNode is not TypeDeclarationSyntax typeDeclarationSyntax)
        {
            return null;
        }

        cancellationToken.ThrowIfCancellationRequested();
        return new PgCompositeToGenerate(typeSymbol, typeDeclarationSyntax);
    }

    public static void ExecutePgCompositeGeneration(
        SourceProductionContext context,
        ImmutableArray<PgCompositeToGenerate?> implementationsToGenerate)
    {
        if (implementationsToGenerate.IsEmpty)
        {
            return;
        }

        foreach (var toGenerate in implementationsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            if (toGenerate is not { } pgCompositeToGenerate)
            {
                continue;
            }

            if (!pgCompositeToGenerate.Validate(context))
            {
                continue;
            }

            if (!pgCompositeToGenerate.IsIFromRow)
            {
                PgFromRowToGenerate? pgFromRowToGenerate =
                    pgCompositeToGenerate.GetPgFromRowToGenerate();
                PgFromRowImplementationGenerator.ExecutePgFromRowGeneration(
                    context,
                    ImmutableArray.Create(pgFromRowToGenerate));
            }

            if (!pgCompositeToGenerate.IsIBindMany)
            {
                PgToParamToGenerate? pgToParamToGenerate =
                    pgCompositeToGenerate.GetPgToParamToGenerate();
                PgToParamImplementationGenerator.ExecutePgToParamGeneration(
                    context,
                    ImmutableArray.Create(pgToParamToGenerate));
            }
            var udtImplementation = GeneratePgCompositeDbTypeImplementation(pgCompositeToGenerate);
            context.AddSource(
                $"{pgCompositeToGenerate.ShortName}.IPgUdt.g.cs",
                SourceText.From(udtImplementation, Encoding.UTF8));
        }
    }

    private static string GeneratePgCompositeDbTypeImplementation(
        PgCompositeToGenerate pgCompositeToGenerate)
    {
        return $$"""
                 // <auto-generated/>
                 #nullable enable
                 
                 using System.Buffers;
                 using Sqlx.Postgres.Result;
                 using Sqlx.Postgres.Type;
                 
                 namespace {{pgCompositeToGenerate.ContainingNamespace}};
                 
                 public partial {{(pgCompositeToGenerate.IsStruct ? "struct" : "class")}} {{pgCompositeToGenerate.ShortName}} : IPgUdt<{{pgCompositeToGenerate.ShortName}}>
                 {
                     public static PgTypeInfo DbType { get; set; } = PgTypeInfo.Unknown;
                     
                     public static string TypeName => "{{pgCompositeToGenerate.PgTypeName.Replace("\"", "\"\"")}}";
                     
                     public static void Encode({{pgCompositeToGenerate.ShortName}} value, IBufferWriter<byte> buffer)
                     {
                         PgRecordEncoder.EncodeRecord(value, buffer);
                     }
                 
                     public static {{pgCompositeToGenerate.ShortName}} DecodeBytes(in PgBinaryValue value)
                     {
                         return PgRecordDecoder.DecodeBinary<{{pgCompositeToGenerate.ShortName}}>(in value);
                     }
                     
                     public static {{pgCompositeToGenerate.ShortName}} DecodeText(in PgTextValue value)
                     {
                         return PgRecordDecoder.DecodeText<{{pgCompositeToGenerate.ShortName}}>(in value);
                     }
                     
                     public static bool IsCompatible(PgTypeInfo typeInfo)
                     {
                         return typeInfo == DbType;
                     }
                 }
                 """;
    }
}
