using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sqlx.Postgres.Generator.Type;

internal class PgEnumImplementationGenerator : ISourceGenerationPipeline<PgEnumToGenerate>
{
    public string AttributeName => "Sqlx.Postgres.Generator.Type.PgEnumAttribute";

    public bool IsValidSyntax(SyntaxNode node, CancellationToken cancellationToken) => node.IsEnum;

    public PgEnumToGenerate? CreateGenerationContext(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol enumSymbol)
        {
            return null;
        }

        cancellationToken.ThrowIfCancellationRequested();
        return new PgEnumToGenerate(enumSymbol);
    }

    public void ExecuteGeneration(SourceProductionContext context, ImmutableArray<PgEnumToGenerate> implementationsToGenerate)
    {
        if (implementationsToGenerate.IsEmpty)
        {
            return;
        }

        var bindBuilder = new StringBuilder(
            """
            // <auto-generated/>
            #nullable enable

            namespace Sqlx.Postgres.Generator.Type;

            public static class PgEnumTypes
            {
            """);

        foreach (PgEnumToGenerate pgEnumToGenerate in implementationsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            context.AddSource(
                $"{pgEnumToGenerate.TypeDefName}.g.cs",
                SourceText.From(GeneratePgEnumWrapperType(pgEnumToGenerate), Encoding.UTF8));

            bindBuilder.AppendLine();
            GeneratePgEnumExtensionsMethods(pgEnumToGenerate, bindBuilder);
        }

        bindBuilder.AppendLine("}");

        context.AddSource(
            "PgEnumTypes.g.cs",
            SourceText.From(bindBuilder.ToString(), Encoding.UTF8));
    }

    private static string GeneratePgEnumWrapperType(PgEnumToGenerate pgEnumToGenerate)
    {
        var name = pgEnumToGenerate.TypeDefName;
        var fullName = pgEnumToGenerate.FullName;
        return
            $$"""
              // <auto-generated/>
              #nullable enable

              namespace Sqlx.Postgres.Generator.Type;

              {{pgEnumToGenerate.DeclaredAccessibility.GetModifierToken()}} abstract class {{name}} : global::Sqlx.Postgres.Type.IPgUdt<{{fullName}}>
              {
                  private {{name}}() {}

                  public static global::Sqlx.Postgres.Type.PgTypeInfo DbType { get; set; } = global::Sqlx.Postgres.Type.PgTypeInfo.Unknown;
                  
                  public static string TypeName => "{{pgEnumToGenerate.PgTypeName}}";
                  
                  public static bool IsCompatible(global::Sqlx.Postgres.Type.PgTypeInfo typeInfo)
                  {
                      return typeInfo == DbType;
                  }

                  public static void Encode({{fullName}} value, global::System.Buffers.IBufferWriter<byte> buffer)
                  {
                      global::Sqlx.Core.Buffer.BufferExtensions.WriteString(buffer, value.ToEncodeString());
                  }

                  public static {{fullName}} DecodeBytes(in global::Sqlx.Postgres.Result.PgBinaryValue value)
                  {
                      var buff = value.Buffer;
                      return {{fullName}}.FromChars(
                          global::Sqlx.Core.Buffer.BufferExtensions.ReadString(ref buff),
                          value.ColumnMetadata);
                  }

                  public static {{fullName}} DecodeText(in global::Sqlx.Postgres.Result.PgTextValue value)
                  {
                      return {{fullName}}.FromChars(value.Chars, value.ColumnMetadata);
                  }
              }
              """;
    }

    private static void GeneratePgEnumExtensionsMethods(
        PgEnumToGenerate pgEnumToGenerate,
        StringBuilder builder)
    {
        var name = pgEnumToGenerate.TypeDefName;
        var typeAccessibility = pgEnumToGenerate.DeclaredAccessibility.GetModifierToken();

        builder.Append("    ")
            .Append(typeAccessibility)
            .Append(" static ValueTask Map")
            .Append(pgEnumToGenerate.ShortName)
            .AppendLine(
            "Async(this global::Sqlx.Postgres.Pool.IPgConnectionPool pgConnectionPool, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.Append("        return pgConnectionPool.MapEnumAsync<")
            .AppendFullName(pgEnumToGenerate)
            .Append(", ")
            .Append(name)
            .AppendLine(">(cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    extension(")
            .AppendFullName(pgEnumToGenerate)
            .AppendLine(" enumValue)");
        builder.AppendLine("    {");

        builder.Append("        ")
            .Append(typeAccessibility)
            .AppendLine(" global::System.ReadOnlySpan<char> ToEncodeString()");
        builder.AppendLine("        {");
        builder.AppendLine("            return enumValue switch");
        builder.AppendLine("            {");
        foreach (var kvp in pgEnumToGenerate.ValueNames)
        {
            builder.Append("                ")
                .AppendFullName(pgEnumToGenerate)
                .Append('.')
                .Append(kvp.Key)
                .Append(" => \"")
                .Append(kvp.Value)
                .AppendLine("\",");
        }

        builder.Append("                _ => throw global::Sqlx.Core.Exceptions.ColumnEncodeException.Create<")
            .AppendFullName(pgEnumToGenerate)
            .Append(">(")
            .Append(pgEnumToGenerate.TypeDefName)
            .AppendLine(
                ".DbType.TypeOid.Inner, $\"Attempted to encode an unknown enum variant, '{enumValue}'\"),");
        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine();

        builder.Append("        ")
            .Append(typeAccessibility)
            .Append(" static ")
            .AppendFullName(pgEnumToGenerate)
            .AppendLine(" FromChars(in global::System.ReadOnlySpan<char> chars, in global::Sqlx.Postgres.Column.PgColumnMetadata columnMetadata)");
        builder.AppendLine("        {");
        builder.AppendLine("            return chars switch");
        builder.AppendLine("            {");
        foreach (var kvp in pgEnumToGenerate.ValueNames)
        {
            builder.Append("                \"")
                .Append(kvp.Value)
                .Append("\" => ")
                .AppendFullName(pgEnumToGenerate)
                .Append('.')
                .Append(kvp.Key)
                .AppendLine(",");
        }

        builder.Append("                _ => throw global::Sqlx.Core.Exceptions.ColumnDecodeException.Create<")
            .AppendFullName(pgEnumToGenerate)
            .AppendLine(
                ", global::Sqlx.Postgres.Column.PgColumnMetadata>(columnMetadata, $\"Attempted to decode an unknown enum variant with name, '{chars}'\"),");
        builder.AppendLine("            };");
        builder.AppendLine("        }");

        builder.AppendLine("    }");
        builder.AppendLine();
    }
}
