using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sqlx.Postgres.Generator.Type;

internal static class PgEnumImplementationGenerator
{
    public static PgEnumToGenerate? GetPgEnumTargetForGeneration(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol enumSymbol)
        {
            return null;
        }

        cancellationToken.ThrowIfCancellationRequested();
        return new PgEnumToGenerate(enumSymbol);
    }

    public static void ExecutePgEnumGeneration(
        ImmutableArray<PgEnumToGenerate?> implementationsToGenerate,
        SourceProductionContext context)
    {
        if (implementationsToGenerate.IsEmpty)
        {
            return;
        }

        var bindBuilder = new StringBuilder(
            """
            // <auto-generated/>
            #nullable enable

            using Sqlx.Core.Exceptions;
            using Sqlx.Core.Result;
            using Sqlx.Postgres.Column;
            using Sqlx.Postgres.Exceptions;
            using Sqlx.Postgres.Pool;
            using Sqlx.Postgres.Query;
            using Sqlx.Postgres.Result;
            using Sqlx.Postgres.Type;

            namespace Sqlx.Postgres.Generator.Type;

            public static class PgEnumTypes
            {
            """);

        foreach (var toGenerate in implementationsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            if (toGenerate is not { } pgEnumToGenerate)
            {
                continue;
            }

            context.AddSource(
                $"{pgEnumToGenerate.TypeDefName}.g.cs",
                SourceText.From(GeneratePgEnumWrapperType(pgEnumToGenerate), Encoding.UTF8));

            bindBuilder.AppendLine();
            GeneratePgEnumExtensionsMethods(pgEnumToGenerate, bindBuilder);
        }

        bindBuilder.AppendLine("}");

        context.AddSource(
            "PgEnumTypes.g.cs",
            SourceText.From(bindBuilder.ToString(), Encoding.UTF8));
    }

    private static string GeneratePgEnumWrapperType(PgEnumToGenerate pgEnumToGenerate)
    {
        var name = pgEnumToGenerate.TypeDefName;
        var fullName = pgEnumToGenerate.FullName;
        return
            $$"""
              // <auto-generated/>
              #nullable enable

              using System.Buffers;
              using Sqlx.Core.Buffer;
              using Sqlx.Postgres.Result;
              using Sqlx.Postgres.Type;

              namespace Sqlx.Postgres.Generator.Type;

              public abstract class {{name}} : IPgUdt<{{fullName}}>
              {
                  private {{name}}() {}

                  public static PgTypeInfo DbType { get; set; } = PgTypeInfo.Unknown;
                  
                  public static string TypeName => "{{pgEnumToGenerate.PgTypeName}}";
                  
                  public static bool IsCompatible(PgTypeInfo typeInfo)
                  {
                      return typeInfo == DbType;
                  }

                  public static void Encode({{fullName}} value, IBufferWriter<byte> buffer)
                  {
                      buffer.WriteString(value.ToEncodeString());
                  }

                  public static {{fullName}} DecodeBytes(ref PgBinaryValue value)
                  {
                      return {{fullName}}.FromChars(value.Buffer.ReadString(), value.ColumnMetadata);
                  }

                  public static {{fullName}} DecodeText(in PgTextValue value)
                  {
                      return {{fullName}}.FromChars(value.Chars, value.ColumnMetadata);
                  }
              }
              """;
    }

    private static void GeneratePgEnumExtensionsMethods(
        PgEnumToGenerate pgEnumToGenerate,
        StringBuilder builder)
    {
        var name = pgEnumToGenerate.TypeDefName;

        builder.Append("    public static ValueTask Map")
            .Append(pgEnumToGenerate.ShortName)
            .AppendLine(
            "Async(this IPgConnectionPool pgConnectionPool, CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.Append("        return pgConnectionPool.MapEnumAsync<")
            .AppendFullName(pgEnumToGenerate)
            .Append(", ")
            .Append(name)
            .AppendLine(">(cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    extension(")
            .AppendFullName(pgEnumToGenerate)
            .AppendLine(" enumValue)");
        builder.AppendLine("    {");

        builder.AppendLine("        public ReadOnlySpan<char> ToEncodeString()");
        builder.AppendLine("        {");
        builder.AppendLine("            return enumValue switch");
        builder.AppendLine("            {");
        foreach (var kvp in pgEnumToGenerate.ValueNames)
        {
            builder.Append("                ")
                .AppendFullName(pgEnumToGenerate)
                .Append('.')
                .Append(kvp.Key)
                .Append(" => \"")
                .Append(kvp.Value)
                .AppendLine("\",");
        }

        builder.Append("                _ => throw ColumnEncodeException.Create<")
            .AppendFullName(pgEnumToGenerate)
            .Append(">(")
            .Append(pgEnumToGenerate.TypeDefName)
            .AppendLine(
                ".DbType.TypeOid.Inner, $\"Attempted to encode an unknown enum variant, '{enumValue}'\"),");
        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine();

        builder.Append("        public static ")
            .AppendFullName(pgEnumToGenerate)
            .AppendLine(" FromChars(in ReadOnlySpan<char> chars, in PgColumnMetadata columnMetadata)");
        builder.AppendLine("        {");
        builder.AppendLine("            return chars switch");
        builder.AppendLine("            {");
        foreach (var kvp in pgEnumToGenerate.ValueNames)
        {
            builder.Append("                \"")
                .Append(kvp.Value)
                .Append("\" => ")
                .AppendFullName(pgEnumToGenerate)
                .Append('.')
                .Append(kvp.Key)
                .AppendLine(",");
        }

        builder.Append("                _ => throw ColumnDecodeException.Create<")
            .AppendFullName(pgEnumToGenerate)
            .AppendLine(
                ", PgColumnMetadata>(columnMetadata, $\"Attempted to decode an unknown enum variant with name, '{chars}'\"),");
        builder.AppendLine("            };");
        builder.AppendLine("        }");

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static void Bind(this IPgBindable pgBindable, ");
        builder.AppendFullName(pgEnumToGenerate);
        builder.AppendLine(" enumValue)");
        builder.AppendLine("    {");
        builder.Append("        pgBindable.Bind<")
            .AppendFullName(pgEnumToGenerate)
            .Append(", ")
            .Append(name)
            .AppendLine(">(enumValue);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static void Bind(this IPgBindable pgBindable, ");
        builder.AppendFullName(pgEnumToGenerate);
        builder.AppendLine("? enumValue)");
        builder.AppendLine("    {");
        builder.Append("        pgBindable.BindVal<")
            .AppendFullName(pgEnumToGenerate)
            .Append(", ")
            .Append(name)
            .AppendLine(">(enumValue);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ")
            .AppendFullName(pgEnumToGenerate)
            .Append(" Get")
            .Append(pgEnumToGenerate.ShortName)
            .AppendLine("NotNull(this IPgDataRow pgDataRow, int index)");
        builder.AppendLine("    {");
        builder.Append("        return pgDataRow.GetPgNotNull<")
            .AppendFullName(pgEnumToGenerate)
            .Append(", ")
            .Append(name)
            .AppendLine(">(index);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ")
            .AppendFullName(pgEnumToGenerate)
            .Append(" Get")
            .Append(pgEnumToGenerate.ShortName)
            .AppendLine("NotNull(this IPgDataRow pgDataRow, string name)");
        builder.AppendLine("    {");
        builder.Append("        return pgDataRow.GetPgNotNull<")
            .AppendFullName(pgEnumToGenerate)
            .Append(", ")
            .Append(name)
            .AppendLine(">(name);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ")
            .AppendFullName(pgEnumToGenerate)
            .Append("? Get")
            .Append(pgEnumToGenerate.ShortName)
            .AppendLine("(this IPgDataRow pgDataRow, int index)");
        builder.AppendLine("    {");
        builder.Append("        return pgDataRow.GetPgVal<")
            .AppendFullName(pgEnumToGenerate)
            .Append(", ")
            .Append(name)
            .AppendLine(">(index);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ")
            .AppendFullName(pgEnumToGenerate)
            .Append("? Get")
            .Append(pgEnumToGenerate.ShortName)
            .AppendLine("(this IPgDataRow pgDataRow, string name)");
        builder.AppendLine("    {");
        builder.Append("        return pgDataRow.GetPgVal<")
            .AppendFullName(pgEnumToGenerate)
            .Append(", ")
            .Append(name)
            .AppendLine(">(name);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }
}
