using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[assembly: InternalsVisibleTo("sqlx-cs-pg-generator-test")]
namespace Sqlx.Postgres.Generator.Type;

[Generator]
internal class PgEnumImplementationGenerator : IIncrementalGenerator
{
    private const string PgEnumAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
        public sealed class PgEnumAttribute : global::System.Attribute
        {
            public required string Name { get; set; }

            public Sqlx.Postgres.Generator.Type.EnumRepresentation Representation  { get; init; } = Sqlx.Postgres.Generator.Type.EnumRepresentation.PgEnum;

            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string EnumRepresentationEnum =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        public enum EnumRepresentation
        {
            Int,
            Text,
            PgEnum,
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "PgNameAttribute.g.cs",
                SourceText.From(SourceGenerationHelper.PgNameAttribute, Encoding.UTF8));
            ctx.AddSource(
                "EnumRepresentation.g.cs",
                SourceText.From(EnumRepresentationEnum, Encoding.UTF8));
            ctx.AddSource(
                "Rename.g.cs",
                SourceText.From(SourceGenerationHelper.RenameEnum, Encoding.UTF8));
            ctx.AddSource(
                "PgEnumAttribute.g.cs",
                SourceText.From(PgEnumAttribute, Encoding.UTF8));
        });

        var typesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Type.PgEnumAttribute",
                predicate: static (_, _) => true,
                transform: GetTargetForGeneration)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            typesToGenerate.Collect(),
            static (spc, source) => Execute(source, spc));
    }

    private static PgEnumToGenerate? GetTargetForGeneration(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol enumSymbol)
        {
            return null;
        }
        cancellationToken.ThrowIfCancellationRequested();
        return new PgEnumToGenerate(enumSymbol);
    }

    private static void Execute(
        ImmutableArray<PgEnumToGenerate?> implementationsToGenerate,
        SourceProductionContext context)
    {
        var bindBuilder = new StringBuilder(
            """
            // <auto-generated/>
            #nullable enable
            
            using Sqlx.Core.Exceptions;
            using Sqlx.Core.Result;
            using Sqlx.Postgres.Column;
            using Sqlx.Postgres.Exceptions;
            using Sqlx.Postgres.Pool;
            using Sqlx.Postgres.Query;
            using Sqlx.Postgres.Result;
            using Sqlx.Postgres.Type;

            namespace Sqlx.Postgres.Generated.Type;

            public static class PgEnumTypes
            {
            """);

        foreach (var toGenerate in implementationsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            if (toGenerate is not { } pgEnumToGenerate)
            {
                continue;
            }

            if (!pgEnumToGenerate.Validate(context))
            {
                continue;
            }

            context.AddSource(
                $"{pgEnumToGenerate.TypeDefName}.g.cs",
                SourceText.From(GeneratePgEnumWrapperType(pgEnumToGenerate), Encoding.UTF8));

            bindBuilder.AppendLine();
            GeneratePgEnumExtensionsMethods(pgEnumToGenerate, bindBuilder);
        }

        bindBuilder.AppendLine("}");

        context.AddSource(
            "PgEnumTypes.g.cs",
            SourceText.From(bindBuilder.ToString(), Encoding.UTF8));
    }

    private static string GeneratePgEnumWrapperType(PgEnumToGenerate pgEnumToGenerate)
    {
        return pgEnumToGenerate.Representation switch
        {
            EnumRepresentation.Int => GenerateIntWrapper(pgEnumToGenerate),
            EnumRepresentation.Text => GenerateTextWrapper(pgEnumToGenerate),
            EnumRepresentation.PgEnum => GeneratePgEnumWrapper(pgEnumToGenerate),
            _ => throw new InvalidOperationException(),
        };

        static string GenerateIntWrapper(PgEnumToGenerate pgEnumToGenerate)
        {
            var name = pgEnumToGenerate.TypeDefName;
            return
                $$"""
                  // <auto-generated/>
                  #nullable enable
                  
                  using System.Buffers;
                  using Sqlx.Core.Buffer;
                  using Sqlx.Core.Exceptions;
                  using Sqlx.Postgres.Result;
                  using Sqlx.Postgres.Type;

                  namespace Sqlx.Postgres.Generated.Type;

                  public abstract class {{name}} : IPgDbType<{{pgEnumToGenerate.Name}}>
                  {
                      private {{name}}() {}

                      public static void Encode({{pgEnumToGenerate.Name}} value, IBufferWriter<byte> buffer)
                      {
                          buffer.WriteInt((int)value);
                      }

                      public static {{pgEnumToGenerate.Name}} DecodeBytes(ref PgBinaryValue value)
                      {
                          return ({{pgEnumToGenerate.Name}})value.Buffer.ReadInt();
                      }

                      public static {{pgEnumToGenerate.Name}} DecodeText(in PgTextValue value)
                      {
                          if (int.TryParse(value.Chars, out var temp))
                          {
                              return ({{pgEnumToGenerate.Name}})temp;
                          }
                          throw ColumnDecodeException.Create<{{pgEnumToGenerate.Name}}>(
                              value.ColumnMetadata,
                              "Could not parse characters into a valid int");
                      }
                      
                      public static PgTypeInfo DbType { get; } = PgTypeInfo.Int4;
                      
                      public static bool IsCompatible(PgTypeInfo typeInfo)
                      {
                          return typeInfo == DbType;
                      }
                  }
                  """;
        }

        static string GenerateTextWrapper(PgEnumToGenerate pgEnumToGenerate)
        {
            var name = pgEnumToGenerate.TypeDefName;
            return
                $$"""
                  // <auto-generated/>
                  #nullable enable
                  
                  using System.Buffers;
                  using Sqlx.Core.Buffer;
                  using Sqlx.Postgres.Result;
                  using Sqlx.Postgres.Type;

                  namespace Sqlx.Postgres.Generated.Type;

                  public abstract class {{name}} : IPgDbType<{{pgEnumToGenerate.Name}}>
                  {
                      private {{name}}() {}

                      public static void Encode({{pgEnumToGenerate.Name}} value, IBufferWriter<byte> buffer)
                      {
                          buffer.WriteString(value.ToEncodeString());
                      }

                      public static {{pgEnumToGenerate.Name}} DecodeBytes(ref PgBinaryValue value)
                      {
                          return {{pgEnumToGenerate.Name}}.FromChars(value.Buffer.ReadString(), value.ColumnMetadata);
                      }

                      public static {{pgEnumToGenerate.Name}} DecodeText(in PgTextValue value)
                      {
                          return {{pgEnumToGenerate.Name}}.FromChars(value.Chars, value.ColumnMetadata);
                      }

                      public static PgTypeInfo DbType { get; } = PgTypeInfo.Text;
                      
                      public static bool IsCompatible(PgTypeInfo typeInfo)
                      {
                          return typeInfo == DbType;
                      }
                  }
                  """;
        }

        static string GeneratePgEnumWrapper(PgEnumToGenerate pgEnumToGenerate)
        {
            var name = pgEnumToGenerate.TypeDefName;
            return
                $$"""
                  // <auto-generated/>
                  #nullable enable

                  using System.Buffers;
                  using Sqlx.Core.Buffer;
                  using Sqlx.Postgres.Result;
                  using Sqlx.Postgres.Type;

                  namespace Sqlx.Postgres.Generated.Type;

                  public abstract class {{name}} : IPgUdt<{{pgEnumToGenerate.Name}}>
                  {
                      private {{name}}() {}

                      public static PgTypeInfo DbType { get; set; } = PgTypeInfo.Unknown;
                      
                      public static string TypeName => "{{pgEnumToGenerate.PgTypeName}}";
                      
                      public static bool IsCompatible(PgTypeInfo typeInfo)
                      {
                          return typeInfo == DbType;
                      }

                      public static void Encode({{pgEnumToGenerate.Name}} value, IBufferWriter<byte> buffer)
                      {
                          buffer.WriteString(value.ToEncodeString());
                      }

                      public static {{pgEnumToGenerate.Name}} DecodeBytes(ref PgBinaryValue value)
                      {
                          return {{pgEnumToGenerate.Name}}.FromChars(value.Buffer.ReadString(), value.ColumnMetadata);
                      }

                      public static {{pgEnumToGenerate.Name}} DecodeText(in PgTextValue value)
                      {
                          return {{pgEnumToGenerate.Name}}.FromChars(value.Chars, value.ColumnMetadata);
                      }
                  }
                  """;
        }
    }

    private static void GeneratePgEnumExtensionsMethods(
        PgEnumToGenerate pgEnumToGenerate,
        StringBuilder builder)
    {
        var name = pgEnumToGenerate.TypeDefName;

        if (pgEnumToGenerate.Representation is EnumRepresentation.PgEnum)
        {
            builder.Append("    public static ValueTask Map");
            builder.Append(pgEnumToGenerate.Name);
            builder.AppendLine(
                "Async(this IPgConnectionPool pgConnectionPool, CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine(
                $"        return pgConnectionPool.MapEnumAsync<{pgEnumToGenerate.Name}, {name}>(cancellationToken);");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        if (pgEnumToGenerate.Representation is not EnumRepresentation.Int)
        {
            builder.Append("    extension(")
                .Append(pgEnumToGenerate.Name)
                .AppendLine(" enumValue)");
            builder.AppendLine("    {");

            builder.AppendLine("        public ReadOnlySpan<char> ToEncodeString()");
            builder.AppendLine("        {");
            builder.AppendLine("            return enumValue switch");
            builder.AppendLine("            {");
            foreach (var kvp in pgEnumToGenerate.ValueNames)
            {
                builder.Append("                ")
                    .Append(pgEnumToGenerate.Name)
                    .Append('.')
                    .Append(kvp.Key)
                    .Append(" => \"")
                    .Append(kvp.Value)
                    .AppendLine("\",");
            }
            builder.Append("                _ => throw ColumnEncodeException.Create<")
                .Append(pgEnumToGenerate.Name)
                .Append(">(")
                .Append(pgEnumToGenerate.TypeDefName)
                .AppendLine(".DbType.TypeOid.Inner, $\"Attempted to encode an unknown enum variant, '{enumValue}'\"),");
            builder.AppendLine("            };");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.AppendLine(
                $"        public static {pgEnumToGenerate.Name} FromChars(in ReadOnlySpan<char> chars, in PgColumnMetadata columnMetadata)");
            builder.AppendLine("        {");
            builder.AppendLine("            return chars switch");
            builder.AppendLine("            {");
            foreach (var kvp in pgEnumToGenerate.ValueNames)
            {
                builder.Append("                \"")
                    .Append(kvp.Value)
                    .Append("\" => ")
                    .Append(pgEnumToGenerate.Name)
                    .Append('.')
                    .Append(kvp.Key)
                    .AppendLine(",");
            }
            builder.Append("                _ => throw ColumnDecodeException.Create<")
                .Append(pgEnumToGenerate.Name)
                .AppendLine(">(columnMetadata, $\"Attempted to decode an unknown enum variant with name, '{chars}'\"),");
            builder.AppendLine("            };");
            builder.AppendLine("        }");

            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.Append("    public static void Bind(this IPgBindable pgBindable, ");
        builder.Append(pgEnumToGenerate.Name);
        builder.AppendLine(" enumValue)");
        builder.AppendLine("    {");
        builder.AppendLine($"        pgBindable.Bind<{pgEnumToGenerate.Name}, {name}>(enumValue);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static void Bind(this IPgBindable pgBindable, ");
        builder.Append(pgEnumToGenerate.Name);
        builder.AppendLine("? enumValue)");
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        pgBindable.BindVal<{pgEnumToGenerate.Name}, {name}>(enumValue);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ");
        builder.Append(pgEnumToGenerate.Name);
        builder.Append(" Get");
        builder.Append(pgEnumToGenerate.Name);
        builder.AppendLine("NotNull(this IPgDataRow pgDataRow, int index)");
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        return pgDataRow.GetPgNotNull<{pgEnumToGenerate.Name}, {name}>(index);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ");
        builder.Append(pgEnumToGenerate.Name);
        builder.Append(" Get");
        builder.Append(pgEnumToGenerate.Name);
        builder.AppendLine("NotNull(this IPgDataRow pgDataRow, string name)");
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        return pgDataRow.GetPgNotNull<{pgEnumToGenerate.Name}, {name}>(name);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ");
        builder.Append(pgEnumToGenerate.Name);
        builder.Append("? Get");
        builder.Append(pgEnumToGenerate.Name);
        builder.AppendLine("(this IPgDataRow pgDataRow, int index)");
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        return pgDataRow.GetPgVal<{pgEnumToGenerate.Name}, {name}>(index);");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ");
        builder.Append(pgEnumToGenerate.Name);
        builder.Append("? Get");
        builder.Append(pgEnumToGenerate.Name);
        builder.AppendLine("(this IPgDataRow pgDataRow, string name)");
        builder.AppendLine("    {");
        builder.AppendLine(
            $"        return pgDataRow.GetPgVal<{pgEnumToGenerate.Name}, {name}>(name);");
        builder.AppendLine("    }");
        builder.AppendLine();
    }
}
