using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sqlx.Postgres.Generator.Type;

[Generator]
public class PgTypeImplementationGenerator : IIncrementalGenerator
{
    private const string WrapperEnumAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
        public sealed class WrapperEnumAttribute : global::System.Attribute
        {
            public required Sqlx.Postgres.Generator.Type.EnumRepresentation Representation  { get; init; }

            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string EnumRepresentationEnum =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        public enum EnumRepresentation
        {
            Int,
            Text,
        }
        """;
    
    private const string PgEnumAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
        public sealed class PgEnumAttribute : global::System.Attribute
        {
            public required string Name { get; set; }

            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string PgNameAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
        public class PgNameAttribute : global::System.Attribute
        {
            public string Value { get; }
            
            public PgNameAttribute(string value)
            {
                Value = value;
            }
        }
        """;

    private const string RenameEnum =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator;

        public enum Rename
        {
            SnakeCase,
            PascalCase,
            CamelCase,
            None,
        }
        """;
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "PgNameAttribute.g.cs",
                SourceText.From(PgNameAttribute, Encoding.UTF8));
            ctx.AddSource(
                "EnumRepresentation.g.cs",
                SourceText.From(EnumRepresentationEnum, Encoding.UTF8));
            ctx.AddSource(
                "Rename.g.cs",
                SourceText.From(RenameEnum, Encoding.UTF8));
            ctx.AddSource(
                "WrapperEnumAttribute.g.cs",
                SourceText.From(WrapperEnumAttribute, Encoding.UTF8));
            ctx.AddSource(
                "PgEnumAttribute.g.cs",
                SourceText.From(PgEnumAttribute, Encoding.UTF8));
        });

        var pgEnumTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Type.PgEnumAttribute",
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: PgEnumImplementationGenerator.GetPgEnumTargetForGeneration)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            pgEnumTypesToGenerate.Collect(),
            static (spc, source) => PgEnumImplementationGenerator.ExecutePgEnumGeneration(source, spc));

        var wrapperEnumTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Type.WrapperEnumAttribute",
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: WrapperEnumImplementationGenerator.GetWrapperEnumTargetForGeneration)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            wrapperEnumTypesToGenerate.Collect(),
            static (spc, source) => WrapperEnumImplementationGenerator.ExecuteWrapperEnumGeneration(source, spc));
    }
}
