using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sqlx.Postgres.Generator.Type;

public class WrapperTypeImplementationGenerator : ISourceGenerationPipeline<WrapperTypeToGenerate>
{
    public string AttributeName => "Sqlx.Postgres.Generator.Type.WrapperTypeAttribute";

    public bool IsValidSyntax(SyntaxNode node, CancellationToken cancellationToken) =>
        node.IsProductType;

    public WrapperTypeToGenerate? CreateGenerationContext(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol ||
            context.TargetNode is not TypeDeclarationSyntax typeDeclarationSyntax)
        {
            return null;
        }

        cancellationToken.ThrowIfCancellationRequested();
        return new WrapperTypeToGenerate(typeSymbol, typeDeclarationSyntax);
    }

    public void ExecuteGeneration(
        SourceProductionContext context,
        ImmutableArray<WrapperTypeToGenerate> item)
    {
        if (item.IsEmpty)
        {
            return;
        }

        foreach (WrapperTypeToGenerate wrapperTypeToGenerate in item)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            if (!wrapperTypeToGenerate.Validate(context))
            {
                continue;
            }

            var dbTypeImplementation = GenerateDbTypeImplementation(wrapperTypeToGenerate);
            context.AddSource(
                $"{wrapperTypeToGenerate.ShortName}.IPgDbType.g.cs",
                SourceText.From(dbTypeImplementation, Encoding.UTF8));
        }
    }

    private static string GenerateDbTypeImplementation(WrapperTypeToGenerate wrapperTypeToGenerate)
    {
        IPropertySymbol innerProperty = wrapperTypeToGenerate.InnerProperty;
        ITypeSymbol innerPropertyType = innerProperty.Type;
        var hasNonDefaultConstructor = wrapperTypeToGenerate.HasNonDefaultConstructor;
        var underLiningType = innerPropertyType.FullName;
        var underLiningDbType = innerPropertyType.GetIPgDbType();
        var namespaceDeclaration = string.IsNullOrEmpty(wrapperTypeToGenerate.ContainingNamespace)
            ? string.Empty
            : $"\n\nnamespace {wrapperTypeToGenerate.ContainingNamespace}";
        return $$"""
                 // <auto-generated/>
                 #nullable enable

                 using Sqlx.Postgres.Result;
                 using Sqlx.Postgres.Type;{{namespaceDeclaration}}

                 {{wrapperTypeToGenerate.DeclaredAccessibility.GetModifierToken()}} partial {{(wrapperTypeToGenerate.IsStruct ? "struct" : "class")}} {{wrapperTypeToGenerate.ShortName}} : IPgDbType<{{wrapperTypeToGenerate.ShortName}}>
                 {
                     private static {{wrapperTypeToGenerate.ShortName}} FromInner({{underLiningType}} inner)
                     {
                         return new {{wrapperTypeToGenerate.ShortName}}{{(hasNonDefaultConstructor ? "(" : $" {{ {innerProperty.Name} = ")}}inner{{(hasNonDefaultConstructor ? ")" : "}")}};
                     }
                 
                     public static PgTypeInfo DbType => {{underLiningDbType}}.DbType;
                     
                     public static void Encode({{wrapperTypeToGenerate.ShortName}} value, IBufferWriter<byte> buffer)
                     {
                         {{underLiningDbType}}.Encode(value.{{innerProperty.Name}}, buffer);
                     }

                     public static {{wrapperTypeToGenerate.ShortName}} DecodeBytes(in PgBinaryValue value)
                     {
                         return FromInner({{underLiningDbType}}.DecodeBytes(in value));
                     }
                     
                     public static {{wrapperTypeToGenerate.ShortName}} DecodeText(in PgTextValue value)
                     {
                         return FromInner({{underLiningDbType}}.DecodeText(in value));
                     }
                     
                     public static bool IsCompatible(PgTypeInfo typeInfo)
                     {
                         return {{underLiningDbType}}.IsCompatible(typeInfo);
                     }
                 }
                 """;
    }
}
