using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[assembly: InternalsVisibleTo("sqlx-cs-pg-generator-test")]
namespace Sqlx.Postgres.Generator.Type;

internal static class WrapperEnumImplementationGenerator
{
    public static WrapperEnumToGenerate? GetWrapperEnumTargetForGeneration(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol enumSymbol)
        {
            return null;
        }

        cancellationToken.ThrowIfCancellationRequested();
        return new WrapperEnumToGenerate(enumSymbol);
    }

    public static void ExecuteWrapperEnumGeneration(
        ImmutableArray<WrapperEnumToGenerate?> implementationsToGenerate,
        SourceProductionContext context)
    {
        if (implementationsToGenerate.IsEmpty)
        {
            return;
        }

        var bindBuilder = new StringBuilder(
            """
            // <auto-generated/>
            #nullable enable

            using Sqlx.Core.Exceptions;
            using Sqlx.Core.Result;
            using Sqlx.Postgres.Column;
            using Sqlx.Postgres.Exceptions;
            using Sqlx.Postgres.Pool;
            using Sqlx.Postgres.Query;
            using Sqlx.Postgres.Result;
            using Sqlx.Postgres.Type;

            namespace Sqlx.Postgres.Generator.Type;

            public static class WrapperEnumTypes
            {
            """);

        foreach (var toGenerate in implementationsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            if (toGenerate is not { } wrapperEnumToGenerate)
            {
                continue;
            }

            if (!wrapperEnumToGenerate.Validate(context))
            {
                continue;
            }

            bindBuilder.AppendLine();
            GenerateWrapperEnumExtensionsMethods(wrapperEnumToGenerate, bindBuilder);
        }

        bindBuilder.AppendLine("}");

        context.AddSource(
            "WrapperEnumTypes.g.cs",
            SourceText.From(bindBuilder.ToString(), Encoding.UTF8));
    }

    private static void GenerateWrapperEnumExtensionsMethods(
        WrapperEnumToGenerate wrapperEnumToGenerate,
        StringBuilder builder)
    {
        if (wrapperEnumToGenerate.Representation is EnumRepresentation.Text)
        {
            builder.Append("    extension(")
                .AppendFullName(wrapperEnumToGenerate)
                .AppendLine(" enumValue)");
            builder.AppendLine("    {");
            builder.AppendLine("        public ReadOnlySpan<char> ToEncodeString()");
            builder.AppendLine("        {");
            builder.AppendLine("            return enumValue switch");
            builder.AppendLine("            {");
            foreach (var kvp in wrapperEnumToGenerate.ValueNames)
            {
                builder.Append("                ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .Append('.')
                    .Append(kvp.Key)
                    .Append(" => \"")
                    .Append(kvp.Value)
                    .AppendLine("\",");
            }

            builder.AppendLine(
                "                _ => throw new InvalidOperationException($\"Attempted to encode an unknown enum variant, '{enumValue}'\"),");
            builder.AppendLine("            };");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.Append("        public static ")
                .AppendFullName(wrapperEnumToGenerate)
                .AppendLine(" FromChars(in ReadOnlySpan<char> chars)");
            builder.AppendLine("        {");
            builder.AppendLine("            return chars switch");
            builder.AppendLine("            {");
            foreach (var kvp in wrapperEnumToGenerate.ValueNames)
            {
                builder.Append("                \"")
                    .Append(kvp.Value)
                    .Append("\" => ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .Append('.')
                    .Append(kvp.Key)
                    .AppendLine(",");
            }

            builder.AppendLine(
                "                _ => throw new InvalidOperationException($\"Attempted to decode an unknown enum variant with name, '{chars}'\"),");
            builder.AppendLine("            };");
            builder.AppendLine("        }");

            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.Append("    public static void Bind(this IPgBindable pgBindable, ");
        builder.AppendFullName(wrapperEnumToGenerate);
        builder.AppendLine(" enumValue)");
        builder.AppendLine("    {");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.AppendLine("        pgBindable.Bind((int)enumValue);");
                break;
            case EnumRepresentation.Text:
                builder.AppendLine("        pgBindable.Bind(enumValue.ToEncodeString());");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static void Bind(this IPgBindable pgBindable, ");
        builder.AppendFullName(wrapperEnumToGenerate);
        builder.AppendLine("? enumValue)");
        builder.AppendLine("    {");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.AppendLine("        if (enumValue.HasValue)");
                builder.AppendLine("        {");
                builder.AppendLine("            pgBindable.Bind((int)enumValue.Value);");
                builder.AppendLine("        }");
                builder.AppendLine("        else");
                builder.AppendLine("        {");
                builder.AppendLine("            pgBindable.BindNull<int>();");
                builder.AppendLine("        }");
                break;
            case EnumRepresentation.Text:
                builder.AppendLine("        if (enumValue.HasValue)");
                builder.AppendLine("        {");
                builder.AppendLine("            pgBindable.Bind(enumValue.Value.ToEncodeString());");
                builder.AppendLine("        }");
                builder.AppendLine("        else");
                builder.AppendLine("        {");
                builder.AppendLine("            pgBindable.BindNull<string>();");
                builder.AppendLine("        }");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ");
        builder.AppendFullName(wrapperEnumToGenerate);
        builder.Append(" Get");
        builder.Append(wrapperEnumToGenerate.ShortName);
        builder.AppendLine("NotNull(this IPgDataRow pgDataRow, int index)");
        builder.AppendLine("    {");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.Append("        return (")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(")pgDataRow.GetIntNotNull(index);");
                break;
            case EnumRepresentation.Text:
                builder.Append("        return ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(".FromChars(pgDataRow.GetStringNotNull(index));");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ");
        builder.AppendFullName(wrapperEnumToGenerate);
        builder.Append(" Get");
        builder.Append(wrapperEnumToGenerate.ShortName);
        builder.AppendLine("NotNull(this IPgDataRow pgDataRow, string name)");
        builder.AppendLine("    {");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.Append("        return (")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(")pgDataRow.GetIntNotNull(name);");
                break;
            case EnumRepresentation.Text:
                builder.Append("        return ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(".FromChars(pgDataRow.GetStringNotNull(name));");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ");
        builder.AppendFullName(wrapperEnumToGenerate);
        builder.Append("? Get");
        builder.Append(wrapperEnumToGenerate.ShortName);
        builder.AppendLine("(this IPgDataRow pgDataRow, int index)");
        builder.AppendLine("    {");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.AppendLine("        if (pgDataRow.IsNull(index)) return null;");
                builder.Append("        return (")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(")pgDataRow.GetIntNotNull(index);");
                break;
            case EnumRepresentation.Text:
                builder.AppendLine("        if (pgDataRow.IsNull(index)) return null;");
                builder.Append("        return ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(".FromChars(pgDataRow.GetStringNotNull(index));");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    public static ");
        builder.AppendFullName(wrapperEnumToGenerate);
        builder.Append("? Get");
        builder.Append(wrapperEnumToGenerate.ShortName);
        builder.AppendLine("(this IPgDataRow pgDataRow, string name)");
        builder.AppendLine("    {");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.AppendLine("        int index = pgDataRow.IndexOf(name);");
                builder.AppendLine("        if (pgDataRow.IsNull(index)) return null;");
                builder.Append("        return (")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(")pgDataRow.GetIntNotNull(index);");
                break;
            case EnumRepresentation.Text:
                builder.AppendLine("        int index = pgDataRow.IndexOf(name);");
                builder.AppendLine("        if (pgDataRow.IsNull(index)) return null;");
                builder.Append("        return ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(".FromChars(pgDataRow.GetStringNotNull(index));");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }
}
