using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sqlx.Postgres.Generator.Type;

internal class WrapperEnumSerdeMethodsGenerator : ISourceGenerationPipeline<WrapperEnumToGenerate>
{
    public string AttributeName => "Sqlx.Postgres.Generator.Type.WrapperEnumAttribute";

    public bool IsValidSyntax(SyntaxNode node, CancellationToken cancellationToken) => node.IsEnum;

    public WrapperEnumToGenerate? CreateGenerationContext(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol enumSymbol ||
            context.TargetNode is not EnumDeclarationSyntax enumDeclarationSyntax)
        {
            return null;
        }

        cancellationToken.ThrowIfCancellationRequested();
        return new WrapperEnumToGenerate(enumSymbol, enumDeclarationSyntax);
    }

    public void ExecuteGeneration(
        SourceProductionContext context,
        ImmutableArray<WrapperEnumToGenerate> implementationsToGenerate)
    {
        if (implementationsToGenerate.IsEmpty)
        {
            return;
        }

        var serdeBuilder = new StringBuilder(
            """
            // <auto-generated/>
            #nullable enable

            namespace Sqlx.Postgres.Generator.Type;

            public static class WrapperEnumTypes
            {
            """);

        foreach (WrapperEnumToGenerate wrapperEnumToGenerate in implementationsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            if (!wrapperEnumToGenerate.Validate(context))
            {
                continue;
            }

            if (wrapperEnumToGenerate.Inner.Representation is not EnumRepresentation.Text)
            {
                continue;
            }

            serdeBuilder.AppendLine();
            GenerateWrapperEnumExtensionsMethods(wrapperEnumToGenerate, serdeBuilder);
        }

        serdeBuilder.AppendLine("}");

        context.AddSource(
            "WrapperEnumTypes.g.cs",
            SourceText.From(serdeBuilder.ToString(), Encoding.UTF8));
    }

    private static void GenerateWrapperEnumExtensionsMethods(
        WrapperEnumToGenerate wrapperEnumToGenerate,
        StringBuilder builder)
    {
        WrapperEnum inner = wrapperEnumToGenerate.Inner;
        var typeAccessibility = inner.DeclaredAccessibility.GetModifierToken();
        builder.Append("    ")
            .Append(typeAccessibility)
            .Append(" static global::System.ReadOnlySpan<char> ")
            .Append(inner.UniqueMethodName)
            .Append('_')
            .Append("ToEncodeString(")
            .AppendFullName(inner)
            .AppendLine(" enumValue)");
        builder.AppendLine("    {");
        builder.AppendLine("        return enumValue switch");
        builder.AppendLine("        {");
        foreach (var kvp in inner.ValueNames)
        {
            builder.Append("            ")
                .AppendFullName(inner)
                .Append('.')
                .Append(kvp.Key)
                .Append(" => \"")
                .Append(kvp.Value)
                .AppendLine("\",");
        }

        builder.AppendLine(
            "            _ => throw new global::System.InvalidOperationException($\"Attempted to encode an unknown enum variant, '{enumValue}'\"),");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    ")
            .Append(typeAccessibility)
            .Append(" static ")
            .AppendFullName(inner)
            .Append(' ')
            .Append(inner.UniqueMethodName)
            .AppendLine("_FromChars(in global::System.ReadOnlySpan<char> chars)");
        builder.AppendLine("    {");
        builder.AppendLine("        return chars switch");
        builder.AppendLine("        {");
        foreach (var kvp in inner.ValueNames)
        {
            builder.Append("            \"")
                .Append(kvp.Value)
                .Append("\" => ")
                .AppendFullName(inner)
                .Append('.')
                .Append(kvp.Key)
                .AppendLine(",");
        }

        builder.AppendLine(
            "            _ => throw new global::System.InvalidOperationException($\"Attempted to decode an unknown enum variant with name, '{chars}'\"),");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
    }
}
