using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sqlx.Postgres.Generator.Type;

internal class WrapperEnumImplementationGenerator : ISourceGenerationPipeline<WrapperEnumToGenerate>
{
    public string AttributeName => "Sqlx.Postgres.Generator.Type.WrapperEnumAttribute";

    public bool IsValidSyntax(SyntaxNode node, CancellationToken cancellationToken) => node.IsEnum;

    public WrapperEnumToGenerate? CreateGenerationContext(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol enumSymbol ||
            context.TargetNode is not EnumDeclarationSyntax enumDeclarationSyntax)
        {
            return null;
        }

        cancellationToken.ThrowIfCancellationRequested();
        return new WrapperEnumToGenerate(enumSymbol, enumDeclarationSyntax);
    }

    public void ExecuteGeneration(
        SourceProductionContext context,
        ImmutableArray<WrapperEnumToGenerate> implementationsToGenerate)
    {
        if (implementationsToGenerate.IsEmpty)
        {
            return;
        }

        var bindBuilder = new StringBuilder(
            """
            // <auto-generated/>
            #nullable enable

            namespace Sqlx.Postgres.Generator.Type;

            public static class WrapperEnumTypes
            {
            """);

        foreach (WrapperEnumToGenerate wrapperEnumToGenerate in implementationsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            if (!wrapperEnumToGenerate.Validate(context))
            {
                continue;
            }

            bindBuilder.AppendLine();
            GenerateWrapperEnumExtensionsMethods(wrapperEnumToGenerate, bindBuilder);
        }

        bindBuilder.AppendLine("}");

        context.AddSource(
            "WrapperEnumTypes.g.cs",
            SourceText.From(bindBuilder.ToString(), Encoding.UTF8));
    }

    private static void GenerateWrapperEnumExtensionsMethods(
        WrapperEnumToGenerate wrapperEnumToGenerate,
        StringBuilder builder)
    {
        var typeAccessibility = wrapperEnumToGenerate.DeclaredAccessibility.GetModifierToken();
        if (wrapperEnumToGenerate.Representation is EnumRepresentation.Text)
        {
            builder.Append("    extension(")
                .AppendFullName(wrapperEnumToGenerate)
                .AppendLine(" enumValue)");
            builder.AppendLine("    {");
            builder.Append("        ")
                .Append(typeAccessibility)
                .AppendLine(" global::System.ReadOnlySpan<char> ToEncodeString()");
            builder.AppendLine("        {");
            builder.AppendLine("            return enumValue switch");
            builder.AppendLine("            {");
            foreach (var kvp in wrapperEnumToGenerate.ValueNames)
            {
                builder.Append("                ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .Append('.')
                    .Append(kvp.Key)
                    .Append(" => \"")
                    .Append(kvp.Value)
                    .AppendLine("\",");
            }

            builder.AppendLine(
                "                _ => throw new global::System.InvalidOperationException($\"Attempted to encode an unknown enum variant, '{enumValue}'\"),");
            builder.AppendLine("            };");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.Append("        ")
                .Append(typeAccessibility)
                .Append(" static ")
                .AppendFullName(wrapperEnumToGenerate)
                .AppendLine(" FromChars(in global::System.ReadOnlySpan<char> chars)");
            builder.AppendLine("        {");
            builder.AppendLine("            return chars switch");
            builder.AppendLine("            {");
            foreach (var kvp in wrapperEnumToGenerate.ValueNames)
            {
                builder.Append("                \"")
                    .Append(kvp.Value)
                    .Append("\" => ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .Append('.')
                    .Append(kvp.Key)
                    .AppendLine(",");
            }

            builder.AppendLine(
                "                _ => throw new global::System.InvalidOperationException($\"Attempted to decode an unknown enum variant with name, '{chars}'\"),");
            builder.AppendLine("            };");
            builder.AppendLine("        }");

            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.Append("    ")
            .Append(typeAccessibility)
            .Append(" static void Bind(this global::Sqlx.Postgres.Query.IPgBindable pgBindable, ")
            .AppendFullName(wrapperEnumToGenerate)
            .AppendLine(" enumValue)");
        builder.AppendLine("    {");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.AppendLine("        pgBindable.Bind((int)enumValue);");
                break;
            case EnumRepresentation.Text:
                builder.AppendLine("        pgBindable.Bind(enumValue.ToEncodeString());");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    ")
            .Append(typeAccessibility)
            .Append(" static void Bind(this global::Sqlx.Postgres.Query.IPgBindable pgBindable, ")
            .AppendFullName(wrapperEnumToGenerate)
            .AppendLine("? enumValue)");
        builder.AppendLine("    {");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.AppendLine("        if (enumValue.HasValue)");
                builder.AppendLine("        {");
                builder.AppendLine("            pgBindable.Bind((int)enumValue.Value);");
                builder.AppendLine("        }");
                builder.AppendLine("        else");
                builder.AppendLine("        {");
                builder.AppendLine("            pgBindable.BindNull<int>();");
                builder.AppendLine("        }");
                break;
            case EnumRepresentation.Text:
                builder.AppendLine("        if (enumValue.HasValue)");
                builder.AppendLine("        {");
                builder.AppendLine(
                    "            pgBindable.Bind(enumValue.Value.ToEncodeString());");
                builder.AppendLine("        }");
                builder.AppendLine("        else");
                builder.AppendLine("        {");
                builder.AppendLine("            pgBindable.BindNull<string>();");
                builder.AppendLine("        }");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    ")
            .Append(typeAccessibility)
            .Append(" static ")
            .AppendFullName(wrapperEnumToGenerate)
            .Append(" Get")
            .Append(wrapperEnumToGenerate.ShortName)
            .AppendLine("NotNull(this global::Sqlx.Postgres.Result.IPgDataRow pgDataRow, int index)");
        builder.AppendLine("    {");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.Append("        return (")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(")pgDataRow.GetPgNotNull<int, global::Sqlx.Postgres.Type.PgInt>(index);");
                break;
            case EnumRepresentation.Text:
                builder.Append("        return ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(".FromChars(pgDataRow.GetPgNotNull<string, global::Sqlx.Postgres.Type.PgString>(index));");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    ")
            .Append(typeAccessibility)
            .Append(" static ")
            .AppendFullName(wrapperEnumToGenerate)
            .Append(" Get")
            .Append(wrapperEnumToGenerate.ShortName)
            .AppendLine("NotNull(this global::Sqlx.Postgres.Result.IPgDataRow pgDataRow, string name)");
        builder.AppendLine("    {");
        builder.AppendLine("        int index = pgDataRow.IndexOf(name);");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.Append("        return (")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(")pgDataRow.GetPgNotNull<int, global::Sqlx.Postgres.Type.PgInt>(index);");
                break;
            case EnumRepresentation.Text:
                builder.Append("        return ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(".FromChars(pgDataRow.GetPgNotNull<string, global::Sqlx.Postgres.Type.PgString>(index));");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    ")
            .Append(typeAccessibility)
            .Append(" static ")
            .AppendFullName(wrapperEnumToGenerate)
            .Append("? Get")
            .Append(wrapperEnumToGenerate.ShortName)
            .AppendLine("(this global::Sqlx.Postgres.Result.IPgDataRow pgDataRow, int index)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (pgDataRow.IsNull(index)) return null;");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.Append("        return (")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(")pgDataRow.GetPgNotNull<int, global::Sqlx.Postgres.Type.PgInt>(index);");
                break;
            case EnumRepresentation.Text:
                builder.Append("        return ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(".FromChars(pgDataRow.GetPgNotNull<string, global::Sqlx.Postgres.Type.PgString>(index));");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    ")
            .Append(typeAccessibility)
            .Append(" static ")
            .AppendFullName(wrapperEnumToGenerate)
            .Append("? Get")
            .Append(wrapperEnumToGenerate.ShortName)
            .AppendLine("(this global::Sqlx.Postgres.Result.IPgDataRow pgDataRow, string name)");
        builder.AppendLine("    {");
        builder.AppendLine("        int index = pgDataRow.IndexOf(name);");
        builder.AppendLine("        if (pgDataRow.IsNull(index)) return null;");
        switch (wrapperEnumToGenerate.Representation)
        {
            case EnumRepresentation.Int:
                builder.Append("        return (")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(")pgDataRow.GetPgNotNull<int, global::Sqlx.Postgres.Type.PgInt>(index);");
                break;
            case EnumRepresentation.Text:
                builder.Append("        return ")
                    .AppendFullName(wrapperEnumToGenerate)
                    .AppendLine(".FromChars(pgDataRow.GetPgNotNull<string, global::Sqlx.Postgres.Type.PgString>(index));");
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }
}
