using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Sqlx.Postgres.Generator.Copy;
using Sqlx.Postgres.Generator.Query;
using Sqlx.Postgres.Generator.Result;
using Sqlx.Postgres.Generator.Type;

namespace Sqlx.Postgres.Generator;

[Generator]
public class PostgresGenerator : IIncrementalGenerator
{
    private const string WrapperEnumAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        /// <summary>
        /// Source generation attribute applied to enum types that will be read from and written to
        /// the database in another simple type. This can either be as text or an integer through
        /// the <see cref="Representation" /> field. You can also set type level rules for how text
        /// values are transformed to the database text if the underlining representation is text.
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
        public sealed class WrapperEnumAttribute : global::System.Attribute
        {
            public required Sqlx.Postgres.Generator.Type.EnumRepresentation Representation  { get; init; }

            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string EnumRepresentationEnum =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        public enum EnumRepresentation
        {
            Int,
            Text,
        }
        """;

    private const string PgEnumAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        /// <summary>
        /// <para>
        /// Source generation attribute applied to enum types that will be read from and written to
        /// the database as a custom Postgres `ENUM` type. The <see cref="Name" /> property supplies
        /// the name of type (schema qualified) to allow for finding the type OID during connection
        /// pool startup. You can also set type level rules for how the enum type labels are mapped
        /// to the database `ENUM` type labels.
        /// </para>
        /// <para>
        /// This attribute also generates an extension method on
        /// <see cref="Sqlx.Postgres.Pool.IPgConnectionPool" /> called `Map{enumName}Async` that
        /// must be called before using the type in any query statements. This fetches the type OID
        /// from the database for subsequent queries.
        /// </para>
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
        public sealed class PgEnumAttribute : global::System.Attribute
        {
            public required string Name { get; init; }

            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string PgCompositeAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        /// <summary>
        /// Source generation attribute applied to class/struct types that will be read from and
        /// written to the database as a custom Postgres composite type. The <see cref="Name" />
        /// property supplies the name of type (schema qualified) to allow for finding the type OID
        /// during connection pool startup. You can also set type level rules for how the property
        /// names are mapped to the database composite type attributes.
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)]
        public sealed class PgCompositeAttribute : global::System.Attribute
        {
            public required string Name { get; init; }

            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string PgPropertySkipAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator;

        /// <summary>
        /// Source generation attribute applied to properties that need to be skipped when
        /// generating serialization or deserialization interfaces for composite, row or parameter
        /// types.
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property)]
        public sealed class PgPropertySkipAttribute : global::System.Attribute
        {
        }
        """;

    private const string PgNameAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator;

        /// <summary>
        /// Source generation attribute applied to properties or parameters that need to use a
        /// different name when generating serialization or deserialization interfaces for enum,
        /// composite or row types. This can also be used for text backed enum wrapper types.
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter)]
        public class PgNameAttribute : global::System.Attribute
        {
            public string Value { get; }
            
            public PgNameAttribute(string value)
            {
                Value = value;
            }
        }
        """;

    private const string RenameEnum =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator;

        public enum Rename
        {
            SnakeCase,
            PascalCase,
            CamelCase,
            None,
        }
        """;

    private const string FromRowAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Result;

        /// <summary>
        /// Source generation attribute applied to class/struct types that represent a single row of
        /// a result. Applying this attribute generates a
        /// <see cref="Sqlx.Core.Result.IFromRow{TDataRow,TResult}"/> implementation that uses the
        /// best constructor or field initializers to create new instances of the type from a given
        /// row. You can also set type level rules for how the property names are mapped to the
        /// field names of the result rows.
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)]
        public sealed class FromRowAttribute : global::System.Attribute
        {
            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string FlattenFieldAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        /// <summary>
        /// Source generation attribute applied to properties that combine 1 or more fields of a
        /// result row into a single type. This type must implement
        /// <see cref="Sqlx.Core.Result.IFromRow{TDataRow,TResult}"/> to allow for the type to
        /// extract the required result fields into a new instance of that type.
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter)]
        public sealed class FlattenFieldAttribute : global::System.Attribute
        {
        }
        """;

    private const string JsonFieldAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        /// <summary>
        /// Source generation attribute applied to properties that represent JSON data from the
        /// database deserialized as the properties type. 
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter)]
        public sealed class JsonFieldAttribute : global::System.Attribute
        {
        }
        """;

    private const string ToParamAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Query;

        /// <summary>
        /// Source generation attribute applied to class/struct types that represent a prepared
        /// statements parameters. Applying this attribute generates a
        /// <see cref="Sqlx.Core.Query.IBindMany{T}"/> implementation where every readable property
        /// is bound to the query in the order they are declared in the type definition.
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)]
        public sealed class ToParamAttribute : global::System.Attribute
        {
        }
        """;

    private const string ToPgBinaryCopyRowAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Copy;

        /// <summary>
        /// Source generation attribute applied to class/struct types that represent a binary copy
        /// in row. Applying this attribute generates a <see cref="Sqlx.Core.Query.IBindMany{T}"/>
        /// implementation where every readable property is bound to the query in the order they are
        /// declared in the type definition as well as the <c>ColumnCount</c> property as the number
        /// of properties found to bind.
        /// </summary>
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)]
        public sealed class ToPgBinaryCopyRowAttribute : global::System.Attribute
        {
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "PgNameAttribute.g.cs",
                SourceText.From(PgNameAttribute, Encoding.UTF8));
            ctx.AddSource(
                "EnumRepresentation.g.cs",
                SourceText.From(EnumRepresentationEnum, Encoding.UTF8));
            ctx.AddSource(
                "Rename.g.cs",
                SourceText.From(RenameEnum, Encoding.UTF8));
            ctx.AddSource(
                "PgPropertySkipAttribute.g.cs",
                SourceText.From(PgPropertySkipAttribute, Encoding.UTF8));
            ctx.AddSource(
                "FlattenFieldAttribute.g.cs",
                SourceText.From(FlattenFieldAttribute, Encoding.UTF8));
            ctx.AddSource(
                "JsonFieldAttribute.g.cs",
                SourceText.From(JsonFieldAttribute, Encoding.UTF8));
            ctx.AddSource(
                "FromRowAttribute.g.cs",
                SourceText.From(FromRowAttribute, Encoding.UTF8));
            ctx.AddSource(
                "ToParamAttribute.g.cs",
                SourceText.From(ToParamAttribute, Encoding.UTF8));
            ctx.AddSource(
                "WrapperEnumAttribute.g.cs",
                SourceText.From(WrapperEnumAttribute, Encoding.UTF8));
            ctx.AddSource(
                "PgEnumAttribute.g.cs",
                SourceText.From(PgEnumAttribute, Encoding.UTF8));
            ctx.AddSource(
                "PgCompositeAttribute.g.cs",
                SourceText.From(PgCompositeAttribute, Encoding.UTF8));
            ctx.AddSource(
                "ToPgBinaryCopyRowAttribute.g.cs",
                SourceText.From(ToPgBinaryCopyRowAttribute, Encoding.UTF8));
        });

        var pgEnumTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Type.PgEnumAttribute",
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: PgEnumImplementationGenerator.GetPgEnumTargetForGeneration)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            pgEnumTypesToGenerate.Collect(),
            static (spc, source) =>
                PgEnumImplementationGenerator.ExecutePgEnumGeneration(source, spc));

        var wrapperEnumTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Type.WrapperEnumAttribute",
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: WrapperEnumImplementationGenerator.GetWrapperEnumTargetForGeneration)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            wrapperEnumTypesToGenerate.Collect(),
            static (spc, source) =>
                WrapperEnumImplementationGenerator.ExecuteWrapperEnumGeneration(source, spc));

        var pgCompositeTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Type.PgCompositeAttribute",
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: PgCompositeImplementationGenerator.GetPgCompositeToGenerate)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            pgCompositeTypesToGenerate.Collect(),
            PgCompositeImplementationGenerator.ExecutePgCompositeGeneration);

        var fromRowTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Result.FromRowAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax
                    or StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: PgFromRowImplementationGenerator.GetPgFromRowToGenerate)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            fromRowTypesToGenerate.Collect(),
            PgFromRowImplementationGenerator.ExecutePgFromRowGeneration);

        var toParamTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Query.ToParamAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax
                    or StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: PgToParamImplementationGenerator.GetPgToParamToGenerate)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            toParamTypesToGenerate.Collect(),
            PgToParamImplementationGenerator.ExecutePgToParamGeneration);

        var toPgBinaryCopyRowTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Copy.ToPgBinaryCopyRowAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax
                    or StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: PgToPgBinaryCopyRowImplementationGenerator.GetPgToPgBinaryCopyRowToGenerate)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            toPgBinaryCopyRowTypesToGenerate.Collect(),
            PgToPgBinaryCopyRowImplementationGenerator.ExecutePgToPgBinaryCopyRowGeneration);
    }
}
