using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Sqlx.Postgres.Generator.Query;
using Sqlx.Postgres.Generator.Result;
using Sqlx.Postgres.Generator.Type;

namespace Sqlx.Postgres.Generator;

[Generator]
public class PostgresGenerator : IIncrementalGenerator
{
    private const string WrapperEnumAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
        public sealed class WrapperEnumAttribute : global::System.Attribute
        {
            public required Sqlx.Postgres.Generator.Type.EnumRepresentation Representation  { get; init; }

            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string EnumRepresentationEnum =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        public enum EnumRepresentation
        {
            Int,
            Text,
        }
        """;
    
    private const string PgEnumAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
        public sealed class PgEnumAttribute : global::System.Attribute
        {
            public required string Name { get; set; }

            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string PgCompositeAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)]
        public sealed class PgCompositeAttribute : global::System.Attribute
        {
            public required string Name { get; set; }

            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string PgPropertySkipAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property)]
        public sealed class PgPropertySkipAttribute : global::System.Attribute
        {
        }
        """;

    private const string PgNameAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter)]
        public class PgNameAttribute : global::System.Attribute
        {
            public string Value { get; }
            
            public PgNameAttribute(string value)
            {
                Value = value;
            }
        }
        """;

    private const string RenameEnum =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator;

        public enum Rename
        {
            SnakeCase,
            PascalCase,
            CamelCase,
            None,
        }
        """;

    private const string FromRowAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Result;
        
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)]
        public sealed class FromRowAttribute : global::System.Attribute
        {
            public Sqlx.Postgres.Generator.Rename RenameAll { get; init; } = Sqlx.Postgres.Generator.Rename.None;
        }
        """;

    private const string FlattenFieldAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;
        
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter)]
        public sealed class FlattenFieldAttribute : global::System.Attribute
        {
        }
        """;

    private const string JsonFieldAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Type;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Property | global::System.AttributeTargets.Parameter)]
        public sealed class JsonFieldAttribute : global::System.Attribute
        {
        }
        """;

    private const string ToParamAttribute =
        """
        // <auto-generated/>
        #nullable enable

        namespace Sqlx.Postgres.Generator.Query;

        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)]
        public sealed class ToParamAttribute : global::System.Attribute
        {
        }
        """;
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "PgNameAttribute.g.cs",
                SourceText.From(PgNameAttribute, Encoding.UTF8));
            ctx.AddSource(
                "EnumRepresentation.g.cs",
                SourceText.From(EnumRepresentationEnum, Encoding.UTF8));
            ctx.AddSource(
                "Rename.g.cs",
                SourceText.From(RenameEnum, Encoding.UTF8));
            ctx.AddSource(
                "PgPropertySkipAttribute.g.cs",
                SourceText.From(PgPropertySkipAttribute, Encoding.UTF8));
            ctx.AddSource(
                "FlattenFieldAttribute.g.cs",
                SourceText.From(FlattenFieldAttribute, Encoding.UTF8));
            ctx.AddSource(
                "JsonFieldAttribute.g.cs",
                SourceText.From(JsonFieldAttribute, Encoding.UTF8));
            ctx.AddSource(
                "FromRowAttribute.g.cs",
                SourceText.From(FromRowAttribute, Encoding.UTF8));
            ctx.AddSource(
                "ToParamAttribute.g.cs",
                SourceText.From(ToParamAttribute, Encoding.UTF8));
            ctx.AddSource(
                "WrapperEnumAttribute.g.cs",
                SourceText.From(WrapperEnumAttribute, Encoding.UTF8));
            ctx.AddSource(
                "PgEnumAttribute.g.cs",
                SourceText.From(PgEnumAttribute, Encoding.UTF8));
            ctx.AddSource(
                "PgCompositeAttribute.g.cs",
                SourceText.From(PgCompositeAttribute, Encoding.UTF8));
        });

        var pgEnumTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Type.PgEnumAttribute",
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: PgEnumImplementationGenerator.GetPgEnumTargetForGeneration)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            pgEnumTypesToGenerate.Collect(),
            static (spc, source) => PgEnumImplementationGenerator.ExecutePgEnumGeneration(source, spc));

        var wrapperEnumTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Type.WrapperEnumAttribute",
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: WrapperEnumImplementationGenerator.GetWrapperEnumTargetForGeneration)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            wrapperEnumTypesToGenerate.Collect(),
            static (spc, source) => WrapperEnumImplementationGenerator.ExecuteWrapperEnumGeneration(source, spc));

        var pgCompositeTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Type.PgCompositeAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: PgCompositeImplementationGenerator.GetPgCompositeToGenerate)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            pgCompositeTypesToGenerate.Collect(),
            PgCompositeImplementationGenerator.ExecutePgCompositeGeneration);

        var fromRowTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Result.FromRowAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: PgFromRowImplementationGenerator.GetPgFromRowToGenerate)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            fromRowTypesToGenerate.Collect(),
            PgFromRowImplementationGenerator.ExecutePgFromRowGeneration);

        var toParamTypesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Sqlx.Postgres.Generator.Query.ToParamAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: PgToParamImplementationGenerator.GetPgToParamToGenerate)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            toParamTypesToGenerate.Collect(),
            PgToParamImplementationGenerator.ExecutePgToParamGeneration);
    }
}
