using Microsoft.CodeAnalysis;

namespace Sqlx.Postgres.Generator;

internal static class SourceGenerationHelper
{
    public static readonly DiagnosticDescriptor DefinitionIsNotPartial =
        new(
            "SQLxPG001",
            "Annotated definition is not partial",
            "'{0}' must be partial to allow for adding implementation details",
            "sqlx-cs-pg Generation",
            DiagnosticSeverity.Error,
            true);
    
    public static readonly DiagnosticDescriptor IntWrapperEnumNotIntBacked =
        new(
            "SQLxPG004",
            "Annotated int wrapper PgEnum is not an int backed enum",
            "'{0}' must be an int backed enum",
            "sqlx-cs-pg Generation",
            DiagnosticSeverity.Error,
            true);

    public const string PgNameAttribute =
        """
        // <auto-generated/>
        #nullable enable
        
        namespace Sqlx.Postgres.Generator;
        
        [global::System.AttributeUsage(validOn: global::System.AttributeTargets.Enum)]
        public class PgNameAttribute : global::System.Attribute
        {
            public string Value { get; }
            
            public PgNameAttribute(string value)
            {
                Value = value;
            }
        }
        """;

    public const string RenameEnum =
        """
        // <auto-generated/>
        #nullable enable
        
        namespace Sqlx.Postgres.Generator;
        
        public enum Rename
        {
            SnakeCase,
            PascalCase,
            CamelCase,
            None,
        }
        """;
}
