using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Sqlx.Postgres.Generator.Query;

namespace Sqlx.Postgres.Generator.Copy;

internal class PgToPgBinaryCopyRowImplementationGenerator : ISourceGenerationPipeline<PgToParamToGenerate>
{
    public string AttributeName => "Sqlx.Postgres.Generator.Copy.ToPgBinaryCopyRowAttribute";

    public bool IsValidSyntax(SyntaxNode node, CancellationToken cancellationToken) =>
        node.IsProductType;

    public PgToParamToGenerate? CreateGenerationContext(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol ||
            context.TargetNode is not TypeDeclarationSyntax typeDeclarationSyntax)
        {
            return null;
        }

        cancellationToken.ThrowIfCancellationRequested();
        return new PgToParamToGenerate(typeSymbol, typeDeclarationSyntax);
    }

    public void ExecuteGeneration(
        SourceProductionContext context,
        ImmutableArray<PgToParamToGenerate> implementationsToGenerate)
    {
        if (implementationsToGenerate.IsEmpty)
        {
            return;
        }

        foreach (PgToParamToGenerate pgToParamToGenerate in implementationsToGenerate)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            if (!pgToParamToGenerate.Validate(context))
            {
                continue;
            }

            PgToParamImplementationGenerator.ExecutePgToParamGeneration(
                context,
                ImmutableArray.Create(pgToParamToGenerate));

            var pgBinaryCopyRowImplementation = GeneratePgBinaryCopyRowTypeImplementation(pgToParamToGenerate);
            context.AddSource(
                $"{pgToParamToGenerate.ShortName}.IPgBinaryCopyRow.g.cs",
                SourceText.From(pgBinaryCopyRowImplementation, Encoding.UTF8));
        }
    }

    private static string GeneratePgBinaryCopyRowTypeImplementation(
        PgToParamToGenerate pgToParamToGenerate)
    {
        StringBuilder builder = new(
            """
            // <auto-generated/>
            #nullable enable

            using Sqlx.Postgres.Copy;
            """);
        builder.AppendLine();
        if (!string.IsNullOrEmpty(pgToParamToGenerate.ContainingNamespace))
        {
            builder.AppendLine();
            builder.Append("namespace ")
                .Append(pgToParamToGenerate.ContainingNamespace)
                .AppendLine(";");
        }
        builder.AppendLine();
        builder.Append(pgToParamToGenerate.DeclaredAccessibility.GetModifierToken())
            .Append(" partial ")
            .Append(pgToParamToGenerate.IsStruct ? "struct " : "class ")
            .Append(pgToParamToGenerate.ShortName)
            .AppendLine(" : IPgBinaryCopyRow");
        builder.AppendLine("{");
        builder.Append("    public static short ColumnCount => ")
            .Append(pgToParamToGenerate.Properties.Length)
            .AppendLine(";");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
